### ISSUE TITLE
main-page.js mantıgı

### ISSUE THREAD

**Issue by ahmetozalp** [abdurrahmanekr/bana-istedigini-sor#1]
misal ben navbar ve topbar eklıcem 2sini ayrı ayrı mı render içinde yazmam lazım?

**Comment by abdurrahmanekr** [comment]
flux'un kendi navbar'ını kullanabilirsin. main-page'de de üstten 60 verirsen navbar olmuş olur

**Comment by abdurrahmanekr** [comment]
eğer kullanmak istemiyorsan render'e kendin yazman gerekir

**Comment by abdurrahmanekr** [comment]
render içine alma derken iki tane kullanamassın bir view'da tek bir render olması gerekir

**Comment by ahmetozalp** [comment]
heh son yazdıgın cevab kafandakı soru işaretini kaldırdı ğekı bunu nasıl yuapıyoruz ben 1 tane toolbar birde navbar eklemek şstşyorum main.page.js ye örnek5.dersde bunları gosterebilirmisin main.page.js şekillendirmeyi

**Comment by abdurrahmanekr** [comment]
5. video şeklinde değilde navbar özelleştirme şekline bir video gelebilir. Zaten elimde anlatılacak çok şey var. Eğer componentleri öğrenmek istiyorsan çok güzel bir [kaynak](https://github.com/react-native-community/react-native-elements) var oraya bak derim

**Comment by ahmetozalp** [comment]
zaten bu kutupaneyi kullanıyorum :) senn form elemenlerını bunlarla degiştirdim ama navbar vs eklemede sıkıntı yaşıyorum b olayıda ogrenmem lazım react native sitesinde bi kkaynak linki atablırmısın ne diye aratıcagımı bılmıyorum bu konuyu çunku
