### ISSUE TITLE
React native sqlite storage undefined is not an object (Evaluating 'NativeModules["SQLite"][method]') hatası

### ISSUE THREAD

**Issue by hakanbeyazit34** [abdurrahmanekr/bana-istedigini-sor#10]
React native sqlite storage dersinizdeki tüm adımları izleyerek kurulumu gerçekleştirip sayfama import ile dahil edip üzerinde işlem yapmaya çalıştığımda 'undefined is not an object (Evaluating 'NativeModules["SQLite"][method]') '     hatası alıyorum. Hatayı daha önce başkaları da almış ve çözüm üretmeye çalışmışlar linkteki gibi. Başarılı olan çözüm yollarını denedim fakat hata hala devam ediyor.Ne yapmam gerekiyor? 
https://github.com/andpor/react-native-sqlite-storage/issues/32

**Comment by abdurrahmanekr** [comment]
@hakanbeyazit34  package.json dosyasını buraya atar mısın ? bende kendim deneyeceğim

**Comment by hakanbeyazit34** [comment]
https://paste.ofcode.org/33qbmhVJWzFNhrqQn74puWU

**Comment by abdurrahmanekr** [comment]
@hakanbeyazit34 projenin package.json demek istemiştim ana dizindeki

**Comment by hakanbeyazit34** [comment]
https://paste.ofcode.org/3bKH6FJ6X4HGh8EuDne7jBF

**Comment by hakanbeyazit34** [comment]
Denediniz mi :)?

**Comment by abdurrahmanekr** [comment]
@hakanbeyazit34 öncelikle ben baştan yükledim uygulamada çalıştırabildim. Kodları direkt olarak yoruma yazsan daha sağlıklı olur linke gitmek yerine buradan okuyabiliriz. O yüzden yorumlarını düzenliyorum. Ben de blogumda bulunan yazıdan faydalandım. test adındaki projemdeki package.json : 
```
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.2",
    "react-native-sqlite-storage": "^3.3.1"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "1.9.2",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
senin package.json dosyanda "@remobile/react-native-sqlite": "^1.0.2" adında bir paket var belki sorunun bundan kaynaklanıyordur. import ettiğin isimlere de dikkat et kütüphanenin ismi bu 
```
react-native-sqlite-storage
```
Bir sıkkıntı ile karşılaşmadım. Eğer sorun giderilemediyse test projesini yayınlayayım oradan bakabilirsiz.

**Comment by hakanbeyazit34** [comment]
Test projesini yayınlarsanız çok iyi olur. Teamviewer ile bağlanıp tekrar benim bilgisayarımda kurarsanız da süper olur:)

**Comment by abdurrahmanekr** [comment]
Siz kendiniz dediklerimi deneyin eğer olmazsa atarım önemli olan Teamviewer olmadan bu işi yapabilmek :)

**Comment by hakanbeyazit34** [comment]
@remobile/react-native-sqlite kurmadan öncede denemiştim olmamış tı . Şimdi sitenizde anlattığınız gibi tekrar kurunca oldu :) . Çok sağol .
