### ISSUE TITLE
React native apk sorunu

### ISSUE THREAD

**Issue by tinim123** [abdurrahmanekr/bana-istedigini-sor#101]
Hocam react native de apk oluşturabiliyorum ama play storede "Hata ayıklama modunda imzalanmış bir APK veya Android App Bundle yüklediniz. APK'nızı veya Android App Bundle'ınızı yayınlama modunda imzalamanız gerekiyor. İmzalama hakkında daha fazla bilgi edinin." hatası alıyorum bunu nasıl çözebilirim

**Comment by tinim123** [comment]
key store ve react native dökümantasyonunda yer alan her adımı yaparak gerçekleştirdim apk almayı, apk çalışıyor ama play store kabul etmiyor

**Comment by abdurrahmanekr** [comment]
android/app/build/outputs/apk/release/ altındaki apk dosyalarını yüklüyorsunuz değil mi?

**Comment by tinim123** [comment]
Evet hocam, sorunu çözdüm apk yüklemek yerine aab dosyasını yükleyerek sorun halledildi fakat şimdide uygulamaya nasıl güncelleme için tekrardan apk veya aab dosyasını alabileceğimi bulamadım, mesela google play da yayınlanan bir uygulamam için güncelleme yayınlamak istiyorum bunu bunun için güncel apk'yı nasıl alabilirim? tekrar dökümantasyon içinde yer alan tüm adımları yapmam mı gerekiyor?

**Comment by abdurrahmanekr** [comment]
Tekrar derlemeniz yeterli o zaman aab veya apk dosyanız güncellenir. Sürüm yönetiminden üretim sürümü yükle kısmından atıp yeni versiyonu gönderebilirsiniz. Tabi android için build.gradle dosyasındaki versionCode değerini de artırmanız gerekir, ben birer birer artırıyorum.

**Comment by tinim123** [comment]
peki çok teşekkür ederim hocam sağolın

**Comment by tinim123** [comment]
Hocam teşekkür edip soruyu kapatmıştım lakin build.gradle içinde yer alan değeri arttırıp sonra derleme yapmalıyım doğru anladım  dimi? bir de siz versionCode değerini arttırın demişsiniz ama orda sadece 1 yazıyor benim uygulamam v1.0 halinde ben bunu 1.0.1 olarak güncelleme istiyorum bunu nasıl yapabilirim?

**Comment by abdurrahmanekr** [comment]
Dediğim değer integer, rakamsal olarak artırmanız gerekiyor

31 May 2020 Paz, saat ÖS 11:52 tarihinde tinim123 <notifications@github.com>
şunu yazdı:

**Comment by tinim123** [comment]
hocam anladım demek istediğinizi sizi baya yordum kusura bakmayın sadece öğrenmeye çalışan biriyim o yüzden böyle oluyor. versionCode u hiç değiştirmeden versionName de yer alan 1.0 değerini değiştirsem playstore de de değişir mi acaba? aslında sormak istediğim şey benim uygulamam playstorede 1.0 olarak görünüyor ben güncelleme çıkarınca bunun 1.0.1 olmasını istiyorum tek yapmak istediğim bu açıkcası

**Comment by abdurrahmanekr** [comment]
Evet play store’a atmadan önce versionName değerini de değiştirmelisiniz,
playstore’a 1.0.1 atmak istiyorsanız versionName değerini 1.0.1 yapıp ve
versionCode değerini artırıp derleyip atmanız lazım

1 Haz 2020 Pzt, saat ÖÖ 12:04 tarihinde tinim123 <notifications@github.com>
şunu yazdı:
