### ISSUE TITLE
React js ile veri listelemek

### ISSUE THREAD

**Issue by mamicrose** [abdurrahmanekr/bana-istedigini-sor#102]

**Comment by abdurrahmanekr** [comment]
İkisi de güvenli bir method, ancak bazı istisnalar var. Örneğin listelemek istediğiniz veriler bazen kullanıcıya gösterilmek istemiyorsanız... Bu anlık kur takibi olur, veya gizli bilgiler olur. Oturum katmanı koymamışsanız eğer yani direkt uygulamayı açan kişi listeyi görebiliyorsa ve gösterdiğiniz bilgiler gizliyse (oturum katmanı derken uygulamayı her açtığında şifre girişi demek istiyorum, banka uygulaması gibi) her zaman sunucudan çekmek daha doğru olandır.

Ancak eğer veri gizliliği ve sonradan oluşan veri sunmama işlemleri gibi işlemler çok önemli değilse SQLite kullanılabilir.

"React js" dediğiniz için web anlıyorum, web'de genellikle SQLite kullanılmaz tamamen sunucu bağımlı olunur. Bu aslında cache kurgularında yaşanan çoğu sorunu da giderir. Çünkü cache yazarken versiyon değişikliği bir geliştirme ister.

Ben web uygulamalarımda client üzerinde veri tutmuyorum. Ama mobil için cache vazgeçilmezim.

Eğer çekeceği liste statik ve değişmez bir şey ise PHP tarafında sürekli DB'den okumak yerine bir cache listesinde tutulabilir. Böylelikle sunucudaki DB i/o azalmış olur.

Giriş yapmak ile ilgili bir konuya değindiniz, bu noktaya takıldım. SQLite ile client üzerinden giriş yaptırma gibi bir işlem düşünüyorsanız vazgeçin, güvenli bir yöntem değil. Kişinin giriş yapabilmesini daima sunucudan sağlayın ve şifresini client üzerinde hiç bir yerde tutmayın.

**Comment by mamicrose** [comment]
Detaylı bilgi için teşekkürler.
Ben react derken mobil geliştiriyorum ve sql kullanımı bana hem zor hem uzun geliyor. aslında demek istediğim react native ile ajax kullanarak DB işlemlerinde sunucuya POST ederek dönen değerleri alsam sizce sağlıklı olur mu?
