### ISSUE TITLE
Sqlite kurulum

### ISSUE THREAD

**Issue by aysegulbozdag** [abdurrahmanekr/bana-istedigini-sor#104]
Meraba, sqlite kurulumunu bir türl gerçekleştiremedim. Yardımcı olur musunuz?

**Comment by abdurrahmanekr** [comment]
Selamlar, tam olarak neyi kuruyorsunuz açıklayabilir misiniz. React Native için mi, örnek uygulamayı deneyerek çözmek isterseniz: https://github.com/abdurrahmanekr/Websql-Sqlite-Service
