### ISSUE TITLE
How do I install Turicreate?

### ISSUE THREAD

**Issue by zynepsivri** [abdurrahmanekr/bana-istedigini-sor#105]
Hi, I am new to machine learning. I need to use the Turicreate library. I tried to install it by looking at some sites but it did not work. I guess it should give a link in this section. I don't understand what's wrong.
Thanks
![Ekran görüntüsü 2020-10-25 160457](https://user-images.githubusercontent.com/72711041/97112676-baff6e00-16f6-11eb-9f43-7696f7e5e7d0.png)

**Comment by abdurrahmanekr** [comment]
hi @zynepsivri  unfortunately i am inexperienced in machine learning. I do not think I can help with this. Sorry :/ have a good day
