### ISSUE TITLE
Electron Güncelleme Sunucusu hatası

### ISSUE THREAD

**Issue by bunyaminmrcn** [abdurrahmanekr/bana-istedigini-sor#106]
Merhabalar . Electron ile uygulama geliştiriyorum. Pek çok yol denedim. Güncelleme sunucusunu ayarlayamadım(generic). En son sizin makalenizi okudum.
Updater sürekli hataya giriyor fakat hata mesajı yazdırmıyor. Yardımcı olabilirmisiniz?.
Makaleniz:
[https://avarekodcu.com/konu/29/electron-uygulamasinin-dagitma-ve-guncelleme-senaryolari](url)

**Comment by bunyaminmrcn** [comment]
Çözüldü

**Comment by abdurrahmanekr** [comment]
Selamlar, sorunu tarayıcıya fix'lemiştim müsait olduğum zaman yanıtlayacaktım da bayağı bi geç kaldım anlaşılan 😄 Çözdüğünüze sevindim :)
