### ISSUE TITLE
Socket.io dosya gönderimi

### ISSUE THREAD

**Issue by emrekayik** [abdurrahmanekr/bana-istedigini-sor#107]
Hocam merhabalar,
socket.io ile realtime file transfer işleri yapmak istiyorum ama pek beceremedim nasıl yapacağım konusunda yardımcı olabilir misiniz?

**Comment by abdurrahmanekr** [comment]
Merhaba @emrekayik

socket.io çok sevdiğim bir konu, realtime dediğine göre şunu bekliyorsun: upload eden kişi ile download eden kişi arasında bir pipe oluşturmak istiyorsun.

Şu anda koddan bahsedemem ama mantıktan bahsedeyim belki yardımcı olur.

- Download eden ve upload eden kişi sisteme bi bağlanırlar, henüz bir iş yapmalarına gerek yok.
- Upload eden kişi dosyayı göndermek için bir nodejs'e bir pipe açar
- nodejs tarafında upload işlemi yakalandığında download eden kişiye bir pipe açar
- upload eden kişinin gönderdiği byte'lar dowload eden kişinin pipe'ına aktarılır ve realtime transfer gerçekleşmiş olur.
