### ISSUE TITLE
discord.js

### ISSUE THREAD

**Issue by eirikaleid** [abdurrahmanekr/bana-istedigini-sor#108]
Hocam discord.js nin 11.6.4 sürümünü kullanıyorum. Bu sürümle normal hesapların tokenleri ile bot yapabiliyorum. Sorum şu , bi link vericem ve otomatik o sunucuya girsin istiyorum. bunu nasıl yaparım ? 

Buraya pek bakamıyorum. eirikaleid@gmail.com mailime mesaj atarsanız sevinirim. teşekkürler

**Comment by abdurrahmanekr** [comment]
Selam, baktığıma göre discord.js client based çalışıyor. Eğer API cors vermiyorsa herhangi bir sitede istediğiniz yapılabilir. Gitlab pages misal

**Comment by eirikaleid** [comment]
hocam peki modem ve pc nin bütün modem tüm güvenlik duvarlarını kapatıp  port açıp http-server kullanıyorum ancak ip adresimi verip kimse gelemiyor siteme.. mailimden ulaşırsanız ya da discord Eirik#7231 çok sevinirim 2,3 yıldır bunu yapmaya çalışıyorum

**Comment by abdurrahmanekr** [comment]
Kişisel bilgisayarınızıdan bir sunum yapmak istiyorsanız buradaki makale işinize yarayabilir: https://gokhansengun.com/kendi-bilgisayarindan-web-sayfasi-sunmak/

**Comment by eirikaleid** [comment]
denedim. maalesef bir şeyler yanlış gitmiş olsa gerek işe yaramadı. Eğer
Zoom ya da TeamViewerden gelip izlemek isterseniz ve akıl verirseniz çok
sevinirim. Windows kullanmama rağmen yazan her şeyi yaptığımı düşünüyorum ,
belki de bilmediğim bir şey vardır.. müsait değilseniz sorun değil , yardım
etmek zorunda değilsiniz. teşekkürler :))
( bu ve 2 makale daha okudum araştırmadan gelmedim )

Avare Kodcu <notifications@github.com>, 11 Şub 2021 Per, 19:18 tarihinde
şunu yazdı:
