### ISSUE TITLE
Merhaba ardunio sorum var

### ISSUE THREAD

**Issue by sLaTeRCoder** [abdurrahmanekr/bana-istedigini-sor#110]
bir ardunio başlangıc seti aldım ve yarın elimde ama farkettim ki c++ ile calışıyormuş ama c++ a daha önce calışmadım udemy e de para vermek istemiyorum napmalıyım ?

**Comment by abdurrahmanekr** [comment]
Merhaba, gördüğüm kadarıyla daha yolun başındasın :) Bazen bazı şeyler hemen olsun isteriz ama çok çile çekmemiz gerektiğini yıllar sonra anlarız :) Donanımı ve geliştirmesini çok severim ama sana öneri verebilecek kadar bilgiye sahip değilim. Genellikle Back-end ve Front-end alanlarına kendimi geliştirdim. Bu durumda YouTube üzerinden ilerleyebilirsin diye düşünüyorum. Ben de çevreden, arkadaşlarımdan vs. videolar izledim. Çok yardımcı olamadım ama umarım iyi bir noktaya getirirsin.
