### ISSUE TITLE
Python Half Trend İndicator Yazımı

### ISSUE THREAD

**Issue by derindusunce** [abdurrahmanekr/bana-istedigini-sor#114]
Merhaba,

Python da halftrend indikatörünü bulamıyourm. Bu indikatörü python da yazabilir miyiz?

indikatör linki :
https://www.tradingview.com/script/U1SJ8ubc-HalfTrend/

**Comment by abdurrahmanekr** [comment]
Merhaba, sorunun üzerinden uzun zaman geçirdiğim için üzgünüm. O yüzden kapatıyorum, sağlıklı günler dilerim.
