### ISSUE TITLE
Electron Uygulamasının, Dağıtma ve Güncelleme Senaryoları

### ISSUE THREAD

**Issue by mustafaisikk** [abdurrahmanekr/bana-istedigini-sor#116]
Merhabalar, yayınladığınız yazı üzerine bir hata ile karşılaşıyorum da yardımcı olabilir misiniz?

Hatam: 

$ npm install && bower install
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated grunt-contrib-uglify-es@3.3.0: deprecated
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated ini@1.1.0: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated ini@1.1.0: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated @mapbox/geojsonhint@2.0.1: Please make plans to check GeoJSON in some other way
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.0.1: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated messageformat@0.3.1: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@4.2.1: this library is no longer supported
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
npm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated ejs@2.3.4: Critical security bugs fixed in 2.5.5
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! Bu çözümde projeler birer birer oluşturuluyor. Paralel oluşturmayı etkinleştirmek için lütfen "/m" anahtarını ekleyin.
npm ERR! Oluşturma başlatıldı: 15.12.2021 15:52:27.
npm ERR! MSBUILD : error MSB4132: Araçların "2.0" sürümü tanınmıyor. Araçların kullanılabilir sürümleri: "4.0".
npm ERR!
npm ERR! Oluşturma BAŞARISIZ OLDU.
npm ERR!
npm ERR!   MSBUILD : error MSB4132: Araçların "2.0" sürümü tanınmıyor. Araçların kullanılabilir sürümleri: "4.0".
npm ERR!
npm ERR!     0 Uyarı
npm ERR!     1 Hata
npm ERR!
npm ERR! Geçen Süre 00:00:00.17
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\mustafa.isik\\Desktop\\tempUpdateElectrons\\helloTemp\\electron-release-server\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb check python launcher python executable found: "C:\\Python27\\python.exe"
npm ERR! gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7.15
npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 16.13.0
npm ERR! gyp verb command install [ '16.13.0' ]
npm ERR! gyp verb install input version string "16.13.0"
npm ERR! gyp verb install installing version: 16.13.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 16.13.0
npm ERR! gyp verb build dir attempting to create "build" dir: C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-sass\build
npm ERR! gyp verb build dir "build" dir needed to be created? C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-sass\build
npm ERR! gyp verb Not using VS2017: Could not use PowerShell to find VS2017
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-sass\build\config.gypi
npm ERR! (node:1404) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp verb config.gypi checking for gypi file: C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-sass\config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-sass\common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "msvs"
npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\mustafa.isik\\Desktop\\tempUpdateElectrons\\helloTemp\\electron-release-server\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-G',
npm ERR! gyp info spawn args   'msvs_version=auto',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\mustafa.isik\\Desktop\\tempUpdateElectrons\\helloTemp\\electron-release-server\\node_modules\\node-sass\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\mustafa.isik\\Desktop\\tempUpdateElectrons\\helloTemp\\electron-release-server\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\mustafa.isik\\.node-gyp\\16.13.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\mustafa.isik\\.node-gyp\\16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\mustafa.isik\\Desktop\\tempUpdateElectrons\\helloTemp\\electron-release-server\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\mustafa.isik\\.node-gyp\\16.13.0\\<(target_arch)\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\mustafa.isik\\Desktop\\tempUpdateElectrons\\helloTemp\\electron-release-server\\node_modules\\node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\mustafa.isik\\Desktop\\tempUpdateElectrons\\helloTemp\\electron-release-server\\node_modules\\node-sass\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
npm ERR! Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
npm ERR! Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
npm ERR! Warning: unrecognized setting VCCLCompilerTool/MultiProcessorCompilation
npm ERR! gyp verb command build []
npm ERR! gyp verb build type Release
npm ERR! gyp verb architecture x64
npm ERR! gyp verb node dev dir C:\Users\mustafa.isik\.node-gyp\16.13.0
npm ERR! gyp verb found first Solution file build/binding.sln
npm ERR! gyp verb could not find "msbuild.exe" in PATH - finding location in registry
npm ERR! gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-gyp\lib\build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mustafa.isik\\Desktop\\tempUpdateElectrons\\helloTemp\\electron-release-server\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\mustafa.isik\Desktop\tempUpdateElectrons\helloTemp\electron-release-server\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mustafa.isik\AppData\Local\npm-cache\_logs\2021-12-15T12_52_33_603Z-debug.log

**Comment by abdurrahmanekr** [comment]
Merhaba, sorunun içerisinde böyle bir çıktı var:
```
MSBUILD : error MSB4132: Araçların "2.0" sürümü tanınmıyor. Araçların kullanılabilir sürümleri: "4.0".
```
Ancak çoğunlukla Windows'ta geliştirme yapmadığım için sorunun sebebini anlayamadım maalesef.

**Comment by mustafaisikk** [comment]
![image](https://user-images.githubusercontent.com/52778108/146192905-3e3f250a-a900-4092-bff5-f43f58f649dc.png)

peki bunu nasıl gerçekleştireceğimi biliyor musunuz?

**Comment by mustafaisikk** [comment]
![image](https://user-images.githubusercontent.com/52778108/146193304-7f0a6020-7185-4635-b57a-eb1986796027.png)

Buradaki adımları denemeye çalıştığımda

![image](https://user-images.githubusercontent.com/52778108/146193235-93b1703c-fcfb-49c8-96c6-148042cb44a6.png)

mesajını alıyorum
