### ISSUE TITLE
hatayı bulamıyorum

### ISSUE THREAD

**Issue by sudecoder** [abdurrahmanekr/bana-istedigini-sor#117]
def func(l):
    even = []
    odd = []
    for i in l :
        if i % 2 == 0:
            even.append(i)
        else:
            odd.append(i)
    return odd , even

yukarıdaki kodda çift sayıları even, tekleri odd listesine ekleyen ve listeleri return eden bir kod yazmak istedim. program hata vermiyor ancak fonksiyonu kullandığımda output alamıyorum. sebebi nedir ?

**Comment by abdurrahmanekr** [comment]
Merhaba sanırsam python ile yapmak istiyorsunuz. buradan bi nedeyin isterseniz: https://www.online-python.com/J8a6Mdwci9

**Comment by abdurrahmanekr** [comment]
@sudecoder bu arada Python boşluğa duyarlı bir dildir, buna dikkat etmek gerekiyor.
