### ISSUE TITLE
sql round kullanımı 

### ISSUE THREAD

**Issue by ahmetenesonder** [abdurrahmanekr/bana-istedigini-sor#118]
![Ekran görüntüsü 2022-12-08 124035](https://user-images.githubusercontent.com/119950343/206412383-2a9fb001-d390-4c31-9c6e-b4cdff87ccf5.png)

Daha acıklayıcı olması amacıyla soruyu direkt görsel ile iletiyorum.  Teşekkür ederim.

**Comment by abdurrahmanekr** [comment]
Öncelikle soruda şaşırdığım kısım name değerinin de çarpılması, soruda bir anlatım bozukluğu olabilir mi? Sanıyorum ki örnekteki sonuç sadece number_grade ve fraction_complated değerlerinin çarpımıyla oluşmuş gibi. Bunu yapmak oldukça basit
```sql
SELECT ROUND(number_grade * fraction_complated) AS percent_complated FROM student_grades
```

**Comment by ahmetenesonder** [comment]
bu sorgu sonucunda oluşan veri sütununu student_grades tablosunun son sütunu olacak şekilde eklemek kısmında sorun yaşıyorum. Eminim basittir yeni yeni öğreniyorum :)

**Comment by abdurrahmanekr** [comment]
O da şu şekilde olmalı: 
```sql
SELECT student_grades.*, ROUND(number_grade * fraction_complated) AS percent_complated FROM student_grades

```

**Comment by ahmetenesonder** [comment]
Teşekkürler.
