### ISSUE TITLE
Github yüklenen proje

### ISSUE THREAD

**Issue by Shepherdsinan** [abdurrahmanekr/bana-istedigini-sor#119]
Github a yüklemiş olduğum projede Türkçe karakterlerde soru işareti veya üzerinde tilda olan y görünmekte nasıl çözebilirim?

**Comment by Shepherdsinan** [comment]
![image](https://user-images.githubusercontent.com/65864888/229373779-08ce0fc1-2a77-4ef7-8e0f-e1eec77b2a4d.png)

**Comment by abdurrahmanekr** [comment]
Sorun editörünüzün kodlama biçimiyle alakalı olabilir, kodlama türünü utf8 yaparsanız çözülebilir

**Comment by Shepherdsinan** [comment]
Visual studio 2022 kullanıyorum farklı kaydet yaparak utf8 yaptım kaydettim düzeldi Teşekkür ederim :)
