### ISSUE TITLE
ionic 2 kurulum başlangıcı

### ISSUE THREAD

**Issue by aydin-faruk** [abdurrahmanekr/bana-istedigini-sor#12]
http://www.avarekodcu.com/konu/9/ionic-2-kurulumu-kullanimi  

bu linkte olan ionic ile ilgili yazınızı okudum. Ve localhosta açılmadı.  Acaba aynı portu kullanan diğer programlar mı var ? Tarayıcıda bu siteye ulaşılamıyor diyor..
Sorun ne olabilir acaba ? Ekran fotolarını atıyorum. yardımcı olursanız sevinirim.

![ionic-start-githubionic](https://user-images.githubusercontent.com/29239513/26853325-31eea4d8-4b1a-11e7-9233-681a638326f8.PNG)
![ionic-serve](https://user-images.githubusercontent.com/29239513/26853334-36ab8284-4b1a-11e7-959f-9cd1f9ae9739.PNG)

**Comment by abdurrahmanekr** [comment]
Merhaba sizde benim düştüğüm hataya düşdünüz :smile: makalede şu yazıyı kalırdınız herhalde :)

> cd ile  githubIonic dizinine geçin cd githubIonic.

yani yapmanız gereken `cd githubIonic` komutunu çalıştırırarak githubIonic dizinine geçmek. umarım sorun çözülmüştür :)

**Comment by aydin-faruk** [comment]
Çok teşekkür ederim. o kadar mutluyum ki şuan. :))
O zaman ionic çalışma başlasın.. İyi çalışmalar. tekrar teşekkür ederim :)
