### ISSUE TITLE
google privacy policy.

### ISSUE THREAD

**Issue by Tugbanurakgun** [abdurrahmanekr/bana-istedigini-sor#124]
Isn't it legal to use 'google_images_search '  python library? due to google privacy policy. I want to use the images I took from Google in the program.

**Comment by abdurrahmanekr** [comment]
Hi, I thought you are using this lib: https://pypi.org/project/Google-Images-Search/
But I don't know about this library, and I guess it is look like a search engine that get images from google. There is no knowledge about privacy policy when you fetch images from internet. So if you fetch images from internet you couldn't have a license. But also google fetch images from internet 🤔 After all if your program works such as search engine, there is no problem i think. But you need legal lawyer to learn this topic.
