### ISSUE TITLE
Electron JS uygulamasına QR makine bağlama

### ISSUE THREAD

**Issue by muhammed-ogz** [abdurrahmanekr/bana-istedigini-sor#127]
Electron Js kullanarak bir otomasyon sistemi hazırlamaya çalışıyorum hocam. ve bu otomasyon sisteminin yanında bilgisayara birkaç adet QR makinesi bağlamamız gerekiyor. Bu işlem mümkün mü, mümkün ise nasıl yapacağım hakkında bilgilendirme yapabilir misiniz ?

**Comment by abdurrahmanekr** [comment]
QR makine nedir tam olarak bilmiyorum, qr code okuyucu bi makine mi demek istediniz?

**Comment by muhammed-ogz** [comment]
evet QR code okuyucu bir makine üzerinde çalışacağız.

**Comment by abdurrahmanekr** [comment]
Elbette dediklerinizi yapabilirsiniz, öncelikle kullanılan okuyucu makine'den verileri nasıl alacağınızı çözmeniz gerekiyor. Diyelim ki makine bir qr kod okudu bunu elektron'a bildirmesi gerekiyor, Ya da electron uygulaması bu makinedeki olayları dinleyerek bir aksiyon olduğunda anlaması gerekiyor. Kullanılan makine için bir sürücü yazılmıştır ve bu sürücüden gelen olayları dinleyen bir exe'yi veya service'i bulmak gerekiyor. Bunu bulduğunuzda electron ile o exe'yi çalıştırabilirsiniz. child_process ile kolayca yapılabilir. Burada daha detaylı bir şekilde çalıştırılacak exe'de olan olayları dinleyebileceğiniz komutlar mevcut: https://stackoverflow.com/a/32872753/5769352

Bir event düştüğünde onu sonra arayüze yansıtmak electron kullandığınız için kolay, ipcMain ipcRenderer ile bu süreçleri yönetirsiniz. İşin uğraştırıcı kısmı makine'ye ait sürücülerle ilgili detayları araştırmanız ve uygulamanızdan makine'yi dinleyebilmeniz önemli. Olayları dinleyebilirseniz geri kalan kısım kolay bi şekilde gelir. not olarak Electron, nodejs alt yapısı kullandığı için bir araştırma yaparken nodejs diye aratmanız daha sağlıklı olur.
