### ISSUE TITLE
ionic framework www klasörü

### ISSUE THREAD

**Issue by b-eyza** [abdurrahmanekr/bana-istedigini-sor#13]
ionic ögrenmeye yeni basladım... kurulumunu yaptım cmd den masaustune  proje olusturuyorum...sublimtext ten  Açıyorum ama www klasöru altında bulunması gereken css img templates gibi seyler yok acaba kurulum sırasında mı bir hata yaptım yardımcı olursanız cok sevinirim... 
ekran görüntüsü de bu sekılde 
https://i.hizliresim.com/5Q4GPL.png

**Comment by abdurrahmanekr** [comment]
Merhaba @b-eyza görünüşe göre ionic 2 klasör yapısı var. İonic 2 ile birlikte src dizininde çalışman gerekiyor. Eğer ionic 1 kullanmak istiyorsan `ionic start <proje adi> --v1` yazmalısın

**Comment by b-eyza** [comment]
evet dediğiniz gibi yapınca onlarda www klasorune geldi... 
https://i.hizliresim.com/PrplV8.png 
ne kadar tesekkür etsem azdır :)   sağolun

**Comment by abdurrahmanekr** [comment]
@b-eyza rica ederim :) Ek olarak hızlı resim kullanmana gerek yok resimleri bu editöre sürükle bırak yaparak da atabilirsin

**Comment by b-eyza** [comment]
peki :) :) :) tekrar cok tesekkurler
