### ISSUE TITLE
react-native

### ISSUE THREAD

**Issue by smhasmha** [abdurrahmanekr/bana-istedigini-sor#15]
merhaba makalelerinizi okudum ,videolarınızı dinledim. React-native öğrenip proje geliştirmek istiyorum ancak ingilizcem çok iyi olmadığı için  kaynaklardan açıkçası çok fazla faydalanamıyorum.? react-native ile sunucu veya web servis bağlantısı nasıl yapabilirim? api ile çektiğim verileri nasıl değerlendiririm,veriler üzerinde nasıl işlem yaparım? react-native in bize sağladığı faydalar neler? örneğin kelimleri işlememiz için özel bir yapısı var mı? react-native i daha etkili öğrenmek için ne tür repertuvarlara sahip olmalıyım. daha önce herhangi bir ortamda native veya hybrid uygulama geliştirmedim .bu işte yeni olanlar için ne gibi tavsiyeleriniz olur? nasıl bir yol gösterirsiniz.bu tarz aklımda bir çok soru var konuları öğrendikçe eminim sorularım çoğalacak. sorularımı maruz görüp yardımcı olursanız memnun olurum.

**Comment by abdurrahmanekr** [comment]
Merhaba @smhasmha soruna (bu aralar işlerim olduğu için) geç cevap veriyorum kusura bakma. Evet gerçekten güzel sorular sorulmuş. Aslında react native'e başlamak adında bir makale yazma düşüncem vardı. Fakat kendime bir ara bulamıyorum. Kafam dağınıkken ve meşgulken yazdığım yazıdan bir hayır gelmiyor :) 
Sorularına vereceğim önemli notlarım şöyle: (twitter üzerinden bir arkadaş daha sormuştu ona verdiğim cevaplara benzeyecek)

> React native nodejs paketleri ile yönetiliyor

> npm bir nodejs paket manager'i yani yöneticisi

> nodejs için yazılmış tüm paketler bazı insanlar tarafından http://npmjs.org  üzerinde tutuluyor
örnek olarak react-native bir npm projesi aynı zamanda
milyonlarca paket var açık paketlerden istediğinizi kullanabilirsiniz.

> react native geliştirmek içi terminal kullanmalısın

>  terminal ise bilgisayarın ta kendisi. Gördüğünüz grafik tarafında oluşturulan her şey aslında terminal ile yapılabilir.

> herhangi bir react-native projesi oluşturmak için illa masaüstü dizinine gerek yok herhangi bir dizine kurabilirsiniz.

> Proje klasörünü açıp komut penceresini orada açtıktan sonra artık yükleyeceğiniz her paket o dizin için geçerlidir (bağımlılıklar için).

> npm install ...... ile istediğin paketi o dizine kurarsın

> package.json ise senin sürekli başka kişilerde tekrar aynı paketleri yüklememen için oluşuturulmuş bilgi paketidir.
 --save ile kurduğun paketleri bu dosyaya kaydedersin

> React native'e başlamak için terminal komutlarını, dizin mantığını öğrenmen gerekir. npm'i ve package.json özelliklerini de.

Şimdiye kadar yazdığım bölüm konuşmamda anlattığım taraftı. Şimdi senin sorunların ile şunları diyebilirim:

> Sunucu veya web servis bağlantısı yapabilirsin. bkz: [networking](https://facebook.github.io/react-native/docs/network.html)

> Gelen değerleri istediğin şekilde değerlendirebilirsin ister state üzerinde ister o class üzerinde react native'in sağladığı avantajları ve bu soruların çoğunu [bu video](https://www.youtube.com/watch?v=X5aMyCvw8aQ)da bulabilirsin

> react native'i anlamak için genellikle uygulamadaki import, export işlemlerini öğrenmen gerekir. Uygulama çoğunlukla callback üzerine kuruldu olduğu için bir method isteğinin nasıl geldiğini iyi kavraman gerekir. this kullanırken gecikmeli fonksiyonlarda this'in değişeceğini öğrenmen gerekiyor, yani bi api isteği bittiğinde sen state üzerinde bir güncelleme yapacaksan o methodu çağırmadan `var self = this;` diyerek yedekleyip onun üzerinde işlem yapmalısın. Bir plugin kurarken onun bağımlıklarını araştırman gerekiyor _gerçekten gerekli mi?_ diye.

Bu şeklide genel sorulara ancak bu kadar cevap verebiliyorum :smile: Yine de aklına takılan ve öğrenmek istediğin soruları buraya sorabilirsin. Ben herkese yardım etmeye çalışıyorum soru için teşekkürler :+1:
