### ISSUE TITLE
Router flux

### ISSUE THREAD

**Issue by hulusimizrak** [abdurrahmanekr/bana-istedigini-sor#16]
Merhabalar,
index.android.js dosyasına 

> import { Router, Scene } from 'react-native-router-flux'; 

ekleyince
![screenshot_1498737760](https://user-images.githubusercontent.com/6283322/27686573-0464ac32-5cdc-11e7-92cc-7adf8a918f7d.png)
hatasını alıyorum. 

Yardımcı olabilir misin ?

**Comment by abdurrahmanekr** [comment]
react-native-router-flux üzerinde bir sorun oluşmuş bu sorunu [burada arayabilirsin](https://github.com/aksonov/react-native-router-flux/issues)
O repository üzerinde oluşan bir sorun neredeyse 1 aydır devam ediyordu ben bir tane [pull request](https://github.com/aksonov/react-native-router-flux/pull/1885) attım. Herhalde en son stabil sürün oydu onu kurabilirsin.
```
npm i react-native-router-flux@3.39.2
```

> Eğer sorun düzelmezse tekrar yorum atabilirsin.

**Comment by hulusimizrak** [comment]
> npm i react-native-router-flux@3.39.2

bu sürümü yükleyemedi, geçersiz dedi

**Comment by abdurrahmanekr** [comment]
Geçersiz diye birşey demiş olamaz :). Ben denedim ve kurabildi. İlk önce sil sonra yükle o zaman. Hatayı yazabilirsen daha iyi olur.

**Comment by hulusimizrak** [comment]
> sidemenu@0.0.1 C:\Users\hulus\Desktop\react-native-sidemenu
>`-- react-native-router-flux@3.39.2  invalid
>`-- react-native-experimental-navigation@0.27.0

**Comment by abdurrahmanekr** [comment]
Verilen hatada dizininiz react-native-sidemenu-master diye geçiyor ama react-native-sidemenu diye kullanılmış. Doğru dizinde olduğunuzdan emin misiniz ? ayrıca sildikten sonra denediniz mi ?

**Comment by hulusimizrak** [comment]
Dizini düzelttim ve silip yükleyeyim dedim ama yine aynı hata :)

**Comment by hulusimizrak** [comment]
> C:\Users\hulus\Desktop\react-native-sidemenu-master>npm i react-native-router-flux@3.39.2
> sidemenu@0.0.1 C:\Users\hulus\Desktop\react-native-sidemenu-master
> `-- react-native-router-flux@3.39.2  invalid

**Comment by abdurrahmanekr** [comment]
Daha önce böyle bir sorunlar karşılaşmadım. Eğer sorunu çözersen buraya dönüş yapmayı unutma :)

**Comment by hulusimizrak** [comment]
çözebilirsek inşallah tabiki yazarım :)

**Comment by hulusimizrak** [comment]
Üstad router-flux yerine navigator kullansak alttaki kodlarda bi sıkıntı var mı müsait zamanda bi göz atabilir misin,

anasayfa --> https://i.hizliresim.com/4M1Dlp.png
index.android.js --> https://i.hizliresim.com/JlqX2W.png]


yapılması istenen anasayfadan başka bi sayfaya geçiş

**Comment by abdurrahmanekr** [comment]
@hulusimizrak navigator kullanımı videoda anlatmıştım oradan bakarak yapabilirsin. Fakat react native'in yeni güncellemesine Navigator kullanımdan kaldırıldı. Onun yerine react-nativigator kullanman gerekiyor. buraya göz at #14 react-native-router-flux kullanmanda sıkıntı olmaması gerekiyor. Onu bir şekilde yanlış yapıyorsun onu bulman gerek.

**Comment by hulusimizrak** [comment]
Yeni proje üzerinden sorunsuz router-flux çalışıyor. 
Github'dan indirdiğim bi projeye ekleyemiyorum
