### ISSUE TITLE
Yatay Uygulama

### ISSUE THREAD

**Issue by mtayyip** [abdurrahmanekr/bana-istedigini-sor#17]
Merhaba
Ionic 3 ile Uygulamanın sadece yatay olarak çalışması için ne yapmam lazım.Yani cihaz dikey tutulsa bile uygulama yatayda çalışmaya devam etmesini istiyorum.

**Comment by abdurrahmanekr** [comment]
Merhaba @mtayyip bu olayı "Screen Orientation" diye arattım ve karşıma çıkan https://ionicframework.com/docs/native/screen-orientation/ bu sayfaya tıkladım. Buradaki işini görür herhalde kullanımı mevcut.
