### ISSUE TITLE
Ionic 3

### ISSUE THREAD

**Issue by mtayyip** [abdurrahmanekr/bana-istedigini-sor#18]
Merhaba
Uygulamayı hem yatay hem dikey de kullanmak istiyorum.Ancak dikey konuma göre butonları mesela 		width: 40%-height: 10%  şeklinde yapmıştım ve yataya çevirince bozuluyor Nasıl bir şey yapabilirim
Teşekkür ederim

**Comment by abdurrahmanekr** [comment]
Merhaba @mtayyip sorunu kapattığın için üzgünüm. Eğer geç cevap verdiğim için kapattıysan sorulara akşam bakabiliyorum. Eğer sorunu bir şekilde çözdüysen tebrik ederim 😊. Eğer sorunu hâlâ çözemediysen yeniden açabilirsin

**Comment by mtayyip** [comment]
Çözdüm teşekkür ederim  😊
