### ISSUE TITLE
Ionic 3

### ISSUE THREAD

**Issue by mtayyip** [abdurrahmanekr/bana-istedigini-sor#19]
Tekrardan merhaba,
1-Uygulamama bir animasyon ekleyip animasyon karaktere ses vermek istiyorum
2-Uygulama içinde bir ses dosyası çalıştırmak istiyorum ancak olmadı
3-Ekrana telefon koyup telefonun içine tuşlar koyup onlara da işlev atamak istiyorum nasıl yapabilirim
Teşekkürler

**Comment by abdurrahmanekr** [comment]
Merhaba @mtayyip soruna uzun süre bakamadım üzgünüm. İonic üzerinde ses çalmak için araştırma yaptığımda [burada bir şeyler](https://ionicframework.com/docs/native/native-audio/) bulabildim. İonic 2 üzerinde çok bilgiye sahip değilim (açıkçası react native'e geçtikten sonra bıraktım).
Uygulamanın içinde bir sanal telefon gibi bir şey yapmak istiyorsun ama daha önce böyle bir konu ile uğraşmadım ne yazık ki sorularına yanıt verecek bilgiye henüz sahip değilim :disappointed: Uğraştığın işler gayet güzel şeyler olmalı :smile: Tebrik ederim :+1:

**Comment by mtayyip** [comment]
Teşekkür ederim 👍
