### ISSUE TITLE
uygulamayı açamıyorum

### ISSUE THREAD

**Issue by ahmetozalp** [abdurrahmanekr/bana-istedigini-sor#2]
Merhaba oglen geliştirdigim uygulama şuan çalıştırmak istedigimde uygulama 1sanye açılıp geri kapanıyor hata yı nerden yapmış olablırım log dosyası vs varmıdır react native de

**Comment by abdurrahmanekr** [comment]
uygulamayı kaldırıp terminalleride kapatıp `npm cache clear` yazdıktan sonra tekrar çalışıtırın belki olur. extra bir log dosyası var mı bilmiyorum ama node js bir hata ile karşılaştığında bunu loglar. hata oluşmuşsada açık terminal penceresinden görebilirsiniz

**Comment by ahmetkeser** [comment]
aynı sorunu yaşamaktayım yardımcı olurmusunuz ?

**Comment by ahmetkeser** [comment]
> Merhaba oglen geliştirdigim uygulama şuan çalıştırmak istedigimde uygulama 1sanye açılıp geri kapanıyor hata yı nerden yapmış olablırım log dosyası vs varmıdır react native de

sorun çözümlendi ise yardımcı olabilirmisin ?
