### ISSUE TITLE
npm paketleri yüklemede karşılaştığım hata

### ISSUE THREAD

**Issue by smhaylmz** [abdurrahmanekr/bana-istedigini-sor#20]
merhaba react-native projelerine bazı npm paketlerini yüklerken ekteki hatayı alıyorum.  ekde ki hatada projeye native-base paketini yüklemeye çalışıyorum. farklı sürümlerle de denedim fakat bir çözüme ulaşamadım.
![image](https://user-images.githubusercontent.com/29422838/28751482-6f1a13da-7511-11e7-81ba-9ce09fdc02e1.png)

react-native de android ortamında çalışıyorum ayrıca bazı npm paketlerinin ios üzerinde çalıştırılmış örneklerine rastlarken android le uyumlu olmuyor maalesef. bu paketleri androidle uyumlu hale getirmenin yolları var mı??(örneğin shoutem/ui)

yardımcı olursanız memnun olurum. teşekkür ederim.

**Comment by abdurrahmanekr** [comment]
Sanırsam sorun bilgisayarında $PATH dizininde **git**'in belirtilmemiş olması. O ekrandayken git komutunu çalıştırınca _git command not found_ şeklinde uyarı veriyorsa, sorunu [burada](https://stackoverflow.com/a/21614660/5769352) çözebilirsin.

shoutem/ui da bulunan çoğu component android uyumlu değil bu durumda yapacak bir şey kalmıyor.

**Comment by smhaylmz** [comment]
paylaştığınız kaynak problemimi çözdü teşekkür ederim.
