### ISSUE TITLE
The development server returned response error code :500

### ISSUE THREAD

**Issue by duranatakann** [abdurrahmanekr/bana-istedigini-sor#21]
![adsiz](https://user-images.githubusercontent.com/26782477/28784710-dfd93f04-761c-11e7-9327-efa3a5e7518f.png)

Abdurrahman bey merhaba ben react native projenizin ikinci aşamasını bitirdim lakin compile ederken  bundle hatası alıyorum sebebi nedir bilginiz var mı?

**Comment by abdurrahmanekr** [comment]
Merhaba hatadan src/pages/login-page/login-page yolunun bir klasör olduğunu, index.js dosyası aradığını fakat bulamadığını çıkardım. src/pages/login-page/login-page bu yoldaki'nin js dosyası olduğuna emin misiniz? yani 'login-page.js' dosyası var mı? Eğer dosya ise komut penceresinden `Ctrl + C` ile çıkın ve `npm cache clean` yazın sonra tekrar `react native start` komutunu çalıştırın.

**Comment by duranatakann** [comment]
uzantı js dosyası fakat  aradaki dosyalardan birinde harf kayması olmuş :) implement ettim  bu seferde navigator hatası aldım 
![adsiz](https://user-images.githubusercontent.com/26782477/28799839-d1d8af1c-7652-11e7-9487-509d5079f23e.png)

**Comment by duranatakann** [comment]
Hocam issue yi kapatabilirsin stack navigate olayını yeni farkettim:) yeni hatalara geçmeyi başarabildim:)

**Comment by abdurrahmanekr** [comment]
Aynen o konuyu [buraya](https://github.com/abdurrahmanekr/ReactNativeLoginApp/issues/4) yönlendirdim. Tamamdır o zaman kolay gelsin :)
