### ISSUE TITLE
Login ekranında Json Parse error

### ISSUE THREAD

**Issue by duranatakann** [abdurrahmanekr/bana-istedigini-sor#22]
![adsiz](https://user-images.githubusercontent.com/26782477/28814599-e6a0fba8-76a6-11e7-890e-b74db7ab1177.png)
hocam  kullanıcı adı:name şifre:pass girince bu hatayı alıyorum

**Comment by abdurrahmanekr** [comment]
Sunucudan gelen değer json değil bu yüzden hata veriyor. 
```javascript
fetch('...')
.then(res => res.json())
...
```
yerine 
```javascript
fetch('...')
.then(res => res.text())
...
```
yap ve gelen yerde debugger at. Gelen hataları görmek için [https://github.com/jhen0409/react-native-debugger](https://github.com/jhen0409/react-native-debugger) kullanabilirsin.

**Comment by duranatakann** [comment]
aynen hocam bende farklı bir çözüm buldum sunucuyu json dönen bir apiye bağlayıncada sorun çözülüyor issueyi kapatabilirsin teşekkürler :)

**Comment by abdurrahmanekr** [comment]
Sorunun çözüldü ise issue'ları kendinde kapatabilirsin benim için bir sıkıntı yok :) Ben yine de kapatayım.
