### ISSUE TITLE
React Native Animations 

### ISSUE THREAD

**Issue by duranatakann** [abdurrahmanekr/bana-istedigini-sor#23]
Tekrardan merhaba Abdurrahman bey  Ben uygulamamda örneğin kayıt ol butonuna tıkladığım zaman sayfa yenilenmeden açılır kayıt penceresi gelmesini istiyorum react native dede jquerydeki gibi buna benzer animasyonlar var mı varsa nasıl kullanabilirim ?

**Comment by abdurrahmanekr** [comment]
Evet [Modal](https://facebook.github.io/react-native/docs/modal.html) Bu tür özellikleri ve örnekleri [doküman](https://facebook.github.io/react-native/docs)ı takip ederek bulabilirsiniz..
