### ISSUE TITLE
router-flux androidbackbutton

### ISSUE THREAD

**Issue by MuhammetYavuzCayli** [abdurrahmanekr/bana-istedigini-sor#24]
Merhaba dostum benim `router-flux` ile ilgili bir sıkıntım var.Bir hata patlamıyor sadece bir child içinden geri dönmeyip uygulamadan çıkıyor. Öncelikle kullandığım OS ve kütüphane versiyonları:
     `Android '6.0.0' `
    "react": "16.0.0-alpha.12",
    "react-native": "0.47.1",
    "react-native-router-flux": "^4.0.0-beta.16",
    "react-native-scrollable-tab-view": "^0.6.7",
Hikaye kısmı:
Derslerde gösterdiğin gibi ben de kendi start-page imi(App.js), login-page imi(Login.js) main-page imi(HomePage.js) oluşturdum. Kendi index.android.js imde `router-flux ı` aynı mantıkla `Router->Scene(root)->Scene` olarak oluşturdum ve tekrar girince AsyncStorage kısmıyla direk kendi HomePage ime geliyorum. HomePage.js de ScrollableTabView ile tabladım (Tablar : Timeline-Friends-Notification-Profile). Buraya kadar bir sıkıntım yok.

Sorun Kısmı:
Ben HomePage.js in altında çağırdığım Profile.js adlı sayfam var(Klasik profil sayfası paylaşımlar) ve UserInfo.js diye kullanıcı bilgilerinin bulunduğu bir sayfam var. Ben Homepage içinde Profil sayfamdan UserInfo'ya bir Router-flux ile gidiyorum ve bir button yardımıyla `Actions.pop()` yapıp geri döüyorum fakat UserInfo'dayken android telefonların `backbuttonuna` bastığım zaman uygulamadan çıkıyor. ben hem button hem de geri tuşuna bastığım zaman da profile dönmek istiyorum.Kısaca bir kod tavsiyesine veya düzgün scene kullanımına ihtiyacım var :) Nasıl yapabilirim ?

Index.android.js Router yapısı: 
![1](https://user-images.githubusercontent.com/29316755/29006732-7ab83d82-7afe-11e7-92e3-90f413a966ac.PNG)

App.js:
![2](https://user-images.githubusercontent.com/29316755/29006759-c236f7fc-7afe-11e7-8e0b-c3a3b9c02005.PNG)

HomePage.js teki ScrollableTabView(Tablar):
![3](https://user-images.githubusercontent.com/29316755/29006756-b7c9d4f6-7afe-11e7-999a-dce5eaab562d.PNG)

Profil sayfam:(Ayarlar ikonuna tıkladığımda `userInfo() {  Actions.UserInfo();  }` fonksiyonuyla UserInfo.js e gidiyorum ama orada android deki geri tuşuna bastığımda uygulamadan çıkıyor)
![5](https://user-images.githubusercontent.com/29316755/29006966-91eea974-7b02-11e7-9a4e-d76965a6d2ea.PNG)

**Comment by MuhammetYavuzCayli** [comment]
Sorunu şöyle çözdüm gibi 👍  bir BackHandler ekleyerek onun addEventListener fonksiyonundan faydalandım. Sürekli catch e atlıyordu ben de catch te sadece return true yaptım false yaparsam yine kapanıyor. en azından ufak bir dipnot olur görenlere:
![6](https://user-images.githubusercontent.com/29316755/29007655-a7cb32ae-7b10-11e7-8235-dffe7db4cf6e.PNG)

**Comment by abdurrahmanekr** [comment]
Sorunu paylaştığın ve çözdüğün için teşekkür ederim. catch kısmına düşen err değişkeninde ne yazıyor? Actions class'ını dahil etmemiş olabilir misin?

**Comment by MuhammetYavuzCayli** [comment]
Merhaba tekrardan cevabın için sağolasın :) Pardon catch e düşmesi `Actions is not defined` benim hatam dediğin gibi Actions ı eklememişim  👍
