### ISSUE TITLE
React native navigator disable back button

### ISSUE THREAD

**Issue by hulusimizrak** [abdurrahmanekr/bana-istedigini-sor#25]
Üstad merhabalar,
navigator yönlendirilmesiyle login olduktan sonra geri dönmemesi için ne yapmamız lazım ?

**Comment by abdurrahmanekr** [comment]
Bunu [serinin son videosunda](https://www.youtube.com/watch?v=RbUp_yaJgTw&t=1031s) anlatmıştım

**Comment by hulusimizrak** [comment]
O videoda router flux ile yaptın diye biliyorum :)

**Comment by abdurrahmanekr** [comment]
Sen ne kullandın peki?

**Comment by hulusimizrak** [comment]
Navigator kullandım router flux'da hata veriyor

**Comment by hulusimizrak** [comment]
Router flux hatası: https://hizliresim.com/VMJEbR

**Comment by abdurrahmanekr** [comment]
Router flux v4 şu an betada diye biliyorum. `npm i --save react-native-router-flux@3.39.2` React'in deprecated olan sürümlerini kullanmamanı tavsiye ederim.

**Comment by hulusimizrak** [comment]
Nette indirdiğim proje sürümü eski sanırım 
https://hizliresim.com/LnqZdj

**Comment by abdurrahmanekr** [comment]
Sanırsam versiyonun sonundaki . yanlış koplayamışsın. 
<img width="218" alt="ekran resmi 2017-08-15 os 5 23 41" src="https://user-images.githubusercontent.com/15075759/29319974-837598e8-81de-11e7-8811-9e17469aed9e.png">

**Comment by hulusimizrak** [comment]
yüklenen sürüm sanırım başka yerleri bozdu 
https://hizliresim.com/r2b66V

**Comment by abdurrahmanekr** [comment]
@hulusimizrak Sorunun kaynağı tam olarak ne bilmiyorum. Belki debug atarak bulabilirsin. debug içi react native debugger kullanabilirsin.

**Comment by hulusimizrak** [comment]
Tamamdır üstad
