### ISSUE TITLE
Bir sorum var RN- facebookads, admob, appodeal

### ISSUE THREAD

**Issue by MuhammetYavuzCayli** [abdurrahmanekr/bana-istedigini-sor#26]
Merhabalar öncelikle, benim iki sorum olacaktı. React native uygulamalarınızda (android&ios) admob, facebook ads gibi reklam verdirme için kullanılan kütüphanelerden hangisini kullanıyorsunuz merak ediyorum. (Maalesef reklamlandırma konusunda react native de pek destek yok olan da expo.io/facebookads hariç normal cihazlarda stabil çalışmıyor denediğim kadarıyla.) Hem android hem de ios da reklam getirmek için bir bilgilendirme videosu çekmeyi düşünüyor musunuz ?

**Comment by abdurrahmanekr** [comment]
Daha önce react native reklam konusuna bakmamıştım. Birkaç araştırma yaptım (Şu an tam olarak alt yapısını bilmiyorum) [böyle](https://github.com/sbugert/react-native-admob) bir kütüphane buldum. Tabi bunu sen denemiş de olabilirsin. Video çekmek güzel bir fikir, hafta sonu bu konuyla uğraşabilirim.

**Comment by MuhammetYavuzCayli** [comment]
Android üzerine geliştirme yapıyorum. Evet dediğiniz admob ayrıca facebookads kütüphanelerini kullandım maalesef (admob: emilatör haricinde release etsem dahi cihazda, facebookads: expo xde hariç) çalışmıyor. Videonuzu bekliyorum

**Comment by abdurrahmanekr** [comment]
Ben admob'u kullandım emülatör üzerinde ve cihazda kullandım. Hem debug modunda hemde release modunda derledim ve reklamlar başarılı bir şekilde çalışıyor. [Bir örnek](https://github.com/abdurrahmanekr/react-native-admob-example) yaptım. Bunu indirip kullanabilirsin. Ayrıca [video](https://www.youtube.com/watch?v=0FKJ6KqnlxM)'da hazır :) Önerin için teşekkürler [blogumda dokümanı](http://www.avarekodcu.com/konu/27/react-native-reklam-yerlestirme-ve-google-admob-kullanimi) da var. İyi bayramlar :)
