### ISSUE TITLE
Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead 

### ISSUE THREAD

**Issue by izmirlibo** [abdurrahmanekr/bana-istedigini-sor#27]
Merhaba
Aşağıdaki kodları nasıl PDO'ya çevirebilirim?

<?php

$user = "social_1"; //veritabanı kullanıcı adı
$pwd = "123456"; //veritabanı şifresi
$host = "localhost"; //mysql server
$db = "social_1"; 

$conn = mysql_connect($host,$user,$pwd);
mysql_select_db($db);

$cekbakalim = mysql_query("SELECT SUM(value) AS total FROM web_stats");
$cekbakalimm = mysql_query("SELECT SUM(today_clicks) AS today FROM user_clicks WHERE today_clicks>'0'");

	while($cek = mysql_fetch_assoc($cekbakalim)){
		$toplam = $cek['total'];
	}
	while($cekk = mysql_fetch_assoc($cekbakalimm)){
		$bugun = $cekk['today'];
	}
	
?>

**Comment by abdurrahmanekr** [comment]
Merhaba, çevireceğin sorgu basit bir sorgu. Bu konuyu araştırma yaparak bulabilirsin burada iyi bir [kaynak](https://www.erbilen.net/pdo-kullanimi/) var, Pdo kullanımından bahsediyor.

**Comment by izmirlibo** [comment]
<?php

$user = "socialme_social"; //veritabanı kullanıcı adı
$pwd = "y57AIFAl8oiy"; //veritabanı şifresi
$host = "localhost"; //mysql server
$db = "socialme_social"; 


$conn = mysql_connect($host,$user,$pwd);
mysql_select_db($db);

$cekbakalim = mysql_query("SELECT SUM(value) AS total FROM web_stats");
$cekbakalimm = mysql_query("SELECT SUM(today_clicks) AS today FROM user_clicks WHERE today_clicks>'0'");


	while($cek = mysql_fetch_assoc($cekbakalim)){
		$toplam = $cek['total'];
	}
	while($cekk = mysql_fetch_assoc($cekbakalimm)){
		$bugun = $cekk['today'];
	}
	
?>


Hocam denedim ama olmuyor bu kodları sizin çevirmeniz mümkünmüdür ?

**Comment by izmirlibo** [comment]
<?php

$user = "social_1"; //veritabanı kullanıcı adı
$pwd = "123456"; //veritabanı şifresi
$host = "localhost"; //mysql server
$db = "social_1"; 


$conn = mysql_connect($host,$user,$pwd);
mysql_select_db($db);

$cekbakalim = mysql_query("SELECT SUM(value) AS total FROM web_stats");
$cekbakalimm = mysql_query("SELECT SUM(today_clicks) AS today FROM user_clicks WHERE today_clicks>'0'");


	while($cek = mysql_fetch_assoc($cekbakalim)){
		$toplam = $cek['total'];
	}
	while($cekk = mysql_fetch_assoc($cekbakalimm)){
		$bugun = $cekk['today'];
	}
	
?>

Hocam denedim ama olmuyor bu kodları sizin çevirebilmeniz mümkünmüdür?

**Comment by abdurrahmanekr** [comment]
Tam olarak nasıl denediniz? Bana bir şeyler gösterin ki size yardımcı olayım. Konu o kadar basit ki bana sanki bir şeyler kaçırmışsınız gibi geldi. Bakın şimdi iki adet sorgu var, ikisinin de amacının ne olduğunu bilmiyorum ama çıkarımım şu:
```php
// ilk sorgu
while($cek = mysql_fetch_assoc($cekbakalim))
{
	$toplam = $cek['total'];
}
```
Burada `$cekbakalim` diye bir çıktıyı döngü kurarak sürekli $toplam değişkenine atıyor. Bunu, size bir önceki yorumumda belirttiğim kaynakta şöyle bir örnek ile yapabilirsiniz:
```php
$cekbakalim = $db->query("SELECT * FROM tablo", PDO::FETCH_ASSOC);
if ( $cekbakalim->rowCount() ){
     foreach( $cekbakalim as $cek ){
          $toplam = $cek['total'];
     }
}
```
Diğer sorgu da buna benzer olduğu için açıklama gereği duymadım. Ek bilgi olarak isterseniz kodlarınızı **`** karakterleri içerisinde yazarak güzel bir görünüm elde edebilirsiniz. İyi çalışmalar :)

**Comment by izmirlibo** [comment]
Hocam ben php dilinden pek anlamıyorum. Denediğim herşey hata veriyor. 3-5 satır kod fazla bişey değil :)
Ben sadece yardım istedim sizden yapabilirmisiniz diye.
Teşekkürler hocam

**Comment by izmirlibo** [comment]
`$conn = mysql_connect($host,$user,$pwd);
mysql_select_db($db);

$cekbakalim = mysql_query("SELECT SUM(value) AS total FROM web_stats");
$cekbakalimm = mysql_query("SELECT SUM(today_clicks) AS today FROM user_clicks WHERE today_clicks>'0'");


	while($cek = mysql_fetch_assoc($cekbakalim)){
		$toplam = $cek['total'];
	}
	while($cekk = mysql_fetch_assoc($cekbakalimm)){
		$bugun = $cekk['today'];
	}`


Çevrilcek kod tam olarak bu hocam :)
