### ISSUE TITLE
ubuntu da geliştirme yapmak için gerekli kurulumlar nasıl yapılıyor ?

### ISSUE THREAD

**Issue by aydnmms** [abdurrahmanekr/bana-istedigini-sor#28]
Hocam saygılar,
linux ubuntuda react native geliştirme yapmak için gerekli uygulamaların kurulumlarını internette araştırdım ama kurulum için makina çorba oldu :).. sırasıyla hangi kurulumları nasıl yapmak gerekiyor?
java,
node,
android sdk,
path ayarlamaları
genymoiton,
vs..?

**Comment by abdurrahmanekr** [comment]
Merhaba, saydıklarınızı sırası ile kurabilirsin. Aslında eğer linux kullanıyorsanız herşey daha kolay.
1. node ve npm kurulumu
```
sudo apt-get install nodejs-legacy
```
2. java ve development kit (JDK) kurulumu
```
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
```
3. Android sdk kurulumu
bunun arayüz ile yapılmasını tavsiye ederim, android studio kurulumu yapmak için [bkz.](https://developer.android.com/studio/install.html)

4. **$PATH** ile ilgili yaşanan sorunlar
Eğer path üzerinde değişiklik yapıldı ise veya diğer kaynaklanan sorunlardan dolayı değişmiş ise sorunlar yaşanabiliyor. Genellikle benim de yaşadığım sorun **ANDROID_HOME** yolunun sürekli olarak silinmesi. Bu sorunu çözmek için [bu adresten](https://stackoverflow.com/a/41137754/5769352) faydalanabilirsiniz. Yalnız **ANDROID_HOME** yoluna sizin bilgisayarınızda sdk'nın bulunduğu dizini vermeniz gerekiyor.

5. Genymotion işlemleri
    Genymotion bilgisayara kurmak için üye olmanız ve ücretini ödemeniz gerekiyor. İsterseniz 30 günlük deneme sürümünü de kullanabilirsiniz. Kurulumu oldukça basit size bir .bin uzantılı bir dosya veriyor bunu uç birimi (terminali) açarak ./<dosya_adi>.bin diye çalıştırmanız yeterli olacaktır.

6. React Native in kendisi
npm dizini eğer root yetkisine bağlı yere kurulmuşsa -g ile kurulan paketler hata veriyor. Bunu önlemek için npm dizinine `chmod 777` ile yetki vererek sorunu kökten çözebilirsiniz fakat bununla uğraşmamak için `sudo npm install -g create-react-native-app` diyerek kurulumu yapabilirsiniz.

7. React projesini oluşturma ve geliştirme
    Onun için [bu adresten](https://facebook.github.io/react-native/docs/getting-started.html) devam edebilirsiniz.

Aklınıza takılan yerleri tekrar sorabilirsiniz. Teşekkürler 👍

**Comment by aydnmms** [comment]
sudo apt-get install oracle-java8-installer
ile aldığım hata ;
Connecting to download.oracle.com (download.oracle.com)|195.175.114.83|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-10-18 11:11:40 ERROR 404: Not Found.

download failed
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java8-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by abdurrahmanekr** [comment]
Merhaba herhalde bu sorun bir ay önce oluşmuş. [Okuduğum kaynağa](https://askubuntu.com/questions/920106/webupd8-oracle-java-7-installer-failing-with-404) göre el ile [sitesine girerek](http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html) indirmeniz gerekiyor.
