### ISSUE TITLE
React Native'e Giriş 

### ISSUE THREAD

**Issue by ozgesurmeli** [abdurrahmanekr/bana-istedigini-sor#29]
İyi Günler Abdurrahman Bey,
Öncelikle bir şey belirtip size teşekkür etmek isterim. İnsanlara yardım etme isteğinizi ve  bu doğrultuda verdiğiniz çabalar gözler önünde. Kendisine yönetilen soruları sizin kadar kısa süre de cevaplayanı henüz görmedim galiba. Bir sürü problemim olmasına rağmen cevap vermeyeceklerini düşündüğüm için(ki profillerinde öyle görülüyor) kendi başıma halletmeye çalıştım . Ama bu sefer size sormak istedim. Ben yaklaşık 5 haftadır stajımı React i detaylı bir şekilde öğrenmeye çalışarak geçirdim. React dökümanlarını ,yayımlanan bloglara kadar okuyup tutoriali denedim .Uygulamalar yaptım. Youtube'dan  videoları izledim.Bu sürede  tutoriallerden bakarak , kavrayarak yaptıklarım arasında marvel den apı ile veri çektim bunları sayfada listeledim; tictactoe uygulaması, react-router, gulp, sass ile bir single page app; ve bir de todolist  uygulaması yaptım. Çalışma ortamım ise vscode, node.js ve npm (create-react-app ile ) üzerinde çalıştım. Şimdi de react native e geçiş yapmak orada da play store de bir sürü örneği olan bir çizim uygulaması yapmak istiyorum. Daha önce hiçbir şekilde bir mobil uygulama gerçekleştirmedim. Onun için nasıl yapılmalı, nasıl bir yol izlenmeli kestiremiyorum. Native bilen bir arkadaş react i kavradığında native de uygulama geliştirmenin kısa sürede olacağını söylediğinden ben de react e detaylı baktım ve proje olarak da bunu belirledim. Sizce neler yapmalı ?Nasıl bir yol izlemeliyim? React Native 'e geçiş nasıl olmalı? Böyle temel düzeyde bir  uygulamayı yapmak ne kadar süre alır? Yaparken neleri gözününde bulundurmalıyım?Durumum hakkında size detaylı bilgi vermek istediğim için upuzun yazmak zorunda kaldım.Lütfen kusurumu mazur görün. Şimdiden teşekkür ederim.

**Comment by abdurrahmanekr** [comment]
Merhaba, gösterdiğiniz ilgi için ben teşekkür ederim. React üzerinde gayet başarılı bir şekilde ilerlediğiniz görünüyor. R-Native bilen arkadaşınızın dediği gibi react'i bilen bir kişi için geliştirme yapmak oldukça kolay. Bu doğrultuda yapmanız gereken react-native geliştirme araçlarını temin etmek ve yapısı hakkında bilgi edinmek. R-Native ile ilk başladığım zamanlar biraz "bilgisiz" şekilde bir [makale](http://www.avarekodcu.com/konu/14/react-native-ilk-bakis-neler-gordum) yazmıştım. Fakat bunun yerine [bu makaleyi](https://hurriyetlabs.com/react-native-%C3%B6%C4%9Frenmek-i%CC%87%C3%A7in-10-neden-e8a356843512) okumanızı tavsiye ederim. Bunun yanında [turkcekaynaklar.com](https://github.com/fatihacet/turkcekaynaklar-com) adresi de açık kaynak olduğu için orada faydalı kaynaklar paylaşılıyor. R-Native'e başlamak istiyorsanız lisans konusunu gözardı edemezsiniz. Bu konuda da [bu makaleyi](https://medium.com/@yurtarmehmet/avukat-olmayanlar-i%C3%A7in-react-patent-tart%C4%B1%C5%9Fmalar%C4%B1n%C4%B1n-bir-%C3%B6zeti-c5183adbee5) okumanızı öneriyorum. Bu arada IOS geliştirme yapmak için Macbook cihazınızın olması gerekiyor. React'te yapılan çok özel ve güzel şeyleri yapamıyorsunuz. Örneğin `View` nesnesine className gibi bir özellik veremiyorsunuz [bkz.](https://github.com/facebook/react-native/issues/7238#issuecomment-214783518) Olur olmaz yerlerde ios destekliyor android desteklemiyor. Plugin gerektiği zaman topluluktan ediniyorsunuz. Bir npm modülü'nün versiyonu değiştiği zaman tüm projenin bozulduğu zamanlar oluyor. React'e göre daha çok bağımlılık kurmanız gerekiyor. Android ve IOS uygumsuzlukları gerçekten can sıkıcı olabiliyor. Bunlara rağmen kaynak bakımından sıkıntı çekeceğinizi düşünmüyorum. Bazı olumsuzluklar zamanla düzeliyor. Yani bir hata ile karşılaştığınızda soru sormalısınız, araştırmalısınız kesinlikle birşeyler bulursunuz. Çektiğim eğitim videolarındaki R-Native ile şu anki R-Native arasında çok şey geldi geçti. Kafamda bir çok yenilikçi (eğitim videoları hakkında) düşünce var fakat şu an zamanımın olmaması beni biraz aksatıyor.

Eğer R-Native kullanmakla ilgili düşünceleriniz tamamsa artık ne araçlar kullanacağınızı anlatarak devam edeyim. Ben geliştirme için fazla araç kullanmıyorum. Fakat gerçekten ihtiyacım olduğundan ve işimi kolaylaştırdığından dolayı şu araçları kullanıyorum:
- [github.com/jhen0409/react-native-debugger](https://github.com/jhen0409/react-native-debugger)
- [genymotion](https://www.genymotion.com/)

Aslında bu kadar. Bana editörüm (Sublime Text) yetiyor gibi :) Geliştirme için eğer unix benzeri işletim sistemi kullanmanızı tavsiye ederim. Windows kullanıyorsanız bence linux'a geçin (kişisel fikrim). Soru sormaktan çekinmeyin... Sağlıcakla...

**Comment by ozgesurmeli** [comment]
Cevabınız ve ilginiz için çok teşekkür ederim. R-Native in kendi dökümanlarını inceliyorum şu an create-react-native-app den bahsediyor. Ben de npm, node,VS Code üzerinde denemeye çalışıyordum . Bunların üzerinde yapmam sıkıntılı mı olacak? Bahsettiğiniz araçlarla yapmak işi daha mı kolaylaştırıyor? Macbook cihazım olmadığından android uygulama yapmayı planlıyorum. Sizin yukarıda bahsettiğiniz araçları nasıl kullanmam gerekiyor?Daha önce linux kullanmadım. Sublime Text' de bir bilgim yok. Görüldüğü üzere bildiklerim çok kısıtlı. Nasıl bir yol haritası çıkarmalıyım ? Gerçekten nasıl yapacağıma dair ufak bir fikrim yok. Kafam karmaşık. Yol göstericiliğinize çokça ihtiyacım var. Bu arada bahsettiğiniz makaleleri hemen incelemeye başlıyorum.  Şimdiden çok çok teşekkür ederim..

**Comment by abdurrahmanekr** [comment]
> Ben de npm, node,VS Code üzerinde denemeye çalışıyordum

Bu proje alt yapısı tamamen nodejs projesi üzerine kurulu yani npm ve node ile ilgili bir sorun yok. VS Code kullanmanız ile ilgili de bir sorun yok bunları kullanmaya devam edebilirsiniz.
Şu an elinizde tüm araçlar var. React Native için Linux şart değil fakat topluluk olarak desteğiniz daha çok olacağı için kurmanızı öneriyorum. En azından (react native'in) kurulumunu yaptıysanız bence birkaç örnek yapmayı deneyin. Örnek yaparak daha hızlı yol alırsınız.

**Comment by ozgesurmeli** [comment]
Şu an söylemiş olduğunuz turkcekaynaklar.com dokumanlarını incelemekteyim.Dediklerinizi birebir deneyip yapmaya gayret edeceğim .  Her şey için ,zamanınızı ayırdığınız için çok teşekkür ederim.

**Comment by abdurrahmanekr** [comment]
Yine bir sorun olursa yeni bir Issue açabilirsin. Yardımcı olmaya çalışacağım... İyi çalışmalar :)
