### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by ahmetozalp** [abdurrahmanekr/bana-istedigini-sor#3]
kullandıgın mavbar mevcutmudur 5.ders de bi navbar eklermısın main-page.js

**Comment by abdurrahmanekr** [comment]
androidde toolbarAndroid diye ios da NavigatorIOS diye var. Ama flux'un sunduğu navbar'ı özelleştirebilirsin o konuya değinirim bir derste

**Comment by ahmetozalp** [comment]
mayısda askerim biraz seri olursak süper olur :)
