### ISSUE TITLE
react native, firebase ile push notification

### ISSUE THREAD

**Issue by yavadi** [abdurrahmanekr/bana-istedigini-sor#30]
react native, firebase kullanarak android ve ios ortamlarında çalışacak push notification eğitimi hazırlayabilir misiniz?
Ben çok uğraştım ama bir türlü yapamadım. Youtube'deki videolar genellikle ios için anlatılmış ve çok karmaşık geliyor.

**Comment by abdurrahmanekr** [comment]
Merhaba, önerinizi dikkate alacağım. Bende o konuda bir iş yapmak istiyordum. Böylelikle ben de öğrenmiş olurum. Bir makale veya video hazırlayana kadar bu issue'yi açık bırakacağım.

**Comment by yavadi** [comment]
İlginiz ve hızlı cavapladığınız için teşekkürler, bir de ne zamana hazırlayabilirsiniz tahmini bir süre var mı acaba :) çünkü bu iş için baya bir sabırsızlanıyorum da :)

**Comment by abdurrahmanekr** [comment]
Siz yine de hazırlıklı olun benim işim belli olmaz :) Belki bu ay içinde olur ama yine de söz veremiyorum tabi.

**Comment by abdurrahmanekr** [comment]
Eğitimi nihayet yazabildim. Öneriniz için tekrar teşekkür ediyorum. İyi okumalar. 
http://www.avarekodcu.com/konu/41/react-native-firebase-push-notification-kurulumu-ios-ve-android-icin

Yeni paylaştığım yazılardan haberdar olmak için [bloguma abone olun](https://feedburner.google.com/fb/a/mailverify?uri=avarekodcu) :)
