### ISSUE TITLE
React Native Kurulumu

### ISSUE THREAD

**Issue by ozgesurmeli** [abdurrahmanekr/bana-istedigini-sor#31]
İyi Günler , sizinle konuştuğumuzdan beri RN için gerekli kurulumları yapmaya çalışıyorum.  Fakat React gibi hemen bir sonuç alamadım.  İşin içine girdikçe farklı kurulumlardan bahsediliyor. create-react-native-app diyip yeni bir proje hazırlayıp bunu npm start diyorum sonuçta benden QR kodunu (expo ile )telefona okutmamı istedi. Bu şekilde olan bir ortam bana geliştirme için yeterli mi?expo yu telefon a indirip bu şekilde bir kurulum  android uygulama yapmaya yeterli olacak mı? Sizin bana soylediğiniz debugger ve genymotion u eklemeye çalıştım(genymotion için virtual box istiyor virtual box kurup içine vscode gibi diğer gerekli kurulumlarımı mı yapmam gerekiyor?)genymotion debugger ı vscode ile nasıl konfigure edebilirim ? İncelediğim dokumanlarda bir proje de hem android hem de ios formu var. Fakat benim oluşturduğum proje de sadece App.js var. Sürekli  konu farklı yerlere geçiyor . Ben nasıl bir kurulum yapmalıyım? Bunun daha anlaşılır bir yolu var mı ? Anlayışınız ve yardımınız için şimdiden teşekkür ederim...

**Comment by abdurrahmanekr** [comment]
Burada https://github.com/abdurrahmanekr/bana-istedigini-sor/issues/28#issuecomment-337474676 Ubuntu için kurulumdan bahsettim. Fakat windows üzerine kurulum yapmadığım için bu konuda tecrübem yok. Fakat ikiside neredeyse aynı yapmanız gerekenler Nodejs, npm, Java jdk, android studio ve virtual box kurmak. VS Code sadece editör onunla ilgili bir işlem yapmanıza gerek yok. VirtualBox sadece genymotion için gerekli kurulumunu yaptıysanız başka bir işlem yapmanıza gerek yok. Aslında ortada bir configure işlemi yok hepsi ayrı çalışıyor. Yani bir yandan Komut penceresi açık diğer yanda editörünüz diğer yanda genymotion diğer yanda debugger (isteğe bağlı) açık olması gerekiyor. Hepsini tek yerden yöneten bir IDE var mı bilmiyorum fakat durum böyle yani.

**Comment by ozgesurmeli** [comment]
Gerçekten iki gündür sizi soru yağmuruna tutup rahatsız ediyorum.Lütfen kusurumu mazur görün. Anlayışınız ve yardımınız için çok çok teşekkür ederim . android studio ve jdk kurup path ayarlarını daha önce birden fazla deneyip kurmayı başaramadım. VSCode android studio yerine kullanılabilir mi?  Yukarıdaki kurulumları yaparsam projeyi nerede yapacağım VSCode kullanmaya devam mı edeceğim? Yoksa başka bir yer de mi çalışacağım?İki gündür kurulumu yapamadım.

**Comment by abdurrahmanekr** [comment]
Android studio sadece SDK paketleri için gerekli oradan API-23'ü indirdikten sonra android studio ile çok fazla bir işiniz kalmıyor. Kodunuzu yine VS Code üzerinde yazabilirsiniz. [Burada](https://medium.com/@ysfzrn/react-native-windows-kurulumu-dce8e46e98c0) windows kurulumunu başından sonuna anlatan bir makale var. Eğer yine de bir sorun olursa mail ile iletişim kurabilirsiniz. İyi günler.

**Comment by ozgesurmeli** [comment]
Evet o makaleyi daha önceden incelemiştim ama android studio ve vscode kafamı karıştırdığından deneyemedim. Şimdi yapmaya çalışağım. Her şey için çok teşekkür ederim :) Size de iyi günler diliyorum
