### ISSUE TITLE
React Native ScrollView sorunu

### ISSUE THREAD

**Issue by aozfen** [abdurrahmanekr/bana-istedigini-sor#32]
Login ekranı yapıyorum ama şöyle bi sıkıntı var ekran yan döndüğü zaman bazı companentler aşağıya kayıyor bunun için scrollview koyuyorum ancak dikey konumda scrollview heightini full yapmıyor. Ben height: 100% veriyorum bu seferde yatay konumda scrollview çalışmıyor.

Dosya yapısı şöyle

node_modules
App.js
components
-Login
--index.js
--RegisterView.js
--LoginView.js

**App.js**
`
render() {
    return (

      <View style={styles.container}>
        <Login />
      </View>

    );
  }
`
**components/Login/index.js**

` render() {
       
        return (
            <ScrollView style={{height:'100%', position:'absolute', width:'100%', backgroundColor: '#cc2e38'}}>
                <Image style={styles.bgImage} source={require('../..//assets/images/home.jpg')} />
                <View style={styles._black}>
                    <KeyboardAvoidingView behavior="position" style={{ marginTop: 80, alignItems: 'center', }}>
                        {this.state.fontLoaded ? ( 
                        <View>
                            <Text style={{ fontFamily: 'Audiowide', fontSize: 50, color: '#fff' }} >
                                TİTLE
                            </Text>
                           
                        </View>
                         ) : null}

                        {this.state.currentView === 1 ? <Login changeView={this.changeView} />
                        : this.state.currentView === 2 ? <Register changeView={this.changeView} />
                        : null } 
                    </KeyboardAvoidingView>
                </View>
            </ScrollView>
        );
    } `

**components/Login/LoginView.js**
` render() {
        return (
            <View style={styles.container}>
                {this.state.fontLoaded ? (
                    <Text style={{
                        color: '#fff',
                        fontSize: 40,
                        fontFamily: 'Raleway'
                   }}>Giriş yap</Text>
                ) : null}
                <View style={{ marginTop: 50,justifyContent: 'center',alignItems: 'center' }}>
                    <TextInput
                        style={styles.txt}
                        onChangeText={(username) => this.setState({ username })}
                        value={this.state.username}
                        underlineColorAndroid="transparent"
                        autoCorrect={false}
                        placeholder="Kullanıcı Adı"
                        placeholderTextColor="#A1A1A1"
                    />
                    <TextInput
                        style={styles.txt}
                        onChangeText={(password) => this.setState({ password })}
                        value={this.state.password}
                        underlineColorAndroid="transparent"
                        autoCorrect={false}
                        placeholder="Şifre"
                        placeholderTextColor="#A1A1A1"
                    />
                   <Button block dark style={{margin:15,backgroundColor: '#0D76C5', borderRadius: 4 }} >
                        <Text style={{ color: '#fff'}}>Giriş Yap</Text>
                   </Button>

                   <Text style={{marginBottom:10, marginTop:10, color:'#fff', fontSize:15}}>veya</Text>

                   <Button block iconLeft style={{margin:15,backgroundColor: '#3897F0', borderRadius: 4 }} >
                        <Icon active name="logo-facebook" />
                        <Text style={{ color: '#fff', marginLeft:10}}>Facebook ile bağlan</Text>
                   </Button>
                   <Text style={styles.textLoginChange} onPress={() =>this.props.changeView(2)} >Hesabın yok mu? Kayıt ol.</Text>
                    
                </View>

            </View>
        )
    }
`

**Comment by abdurrahmanekr** [comment]
Merhaba ScrollView'ın style'ı `{position: 'absolute'}` olduğu için olabilir. [FlexBox](https://facebook.github.io/react-native/docs/flexbox.html) kullanmanızı öneririm.
```javascript
<ScrollView
    style={{
        display: 'flex',
        backgroundColor: '#cc2e38'
    }}></ScrollView>
```
