### ISSUE TITLE
React.js de local resource den ses oynatma

### ISSUE THREAD

**Issue by aozfen** [abdurrahmanekr/bana-istedigini-sor#33]
Merhaba, bir çok paket gezdim fakat hepsi localden ses okumaya izin vermiyor. Hepsi ya sunucuda yada başka bir kaynakta olmasını istiyor. Belki ben bi yerde gözden bişey kaçırıyorum yada gerekli paketi bulamadım. Sizin bildiğiniz paket varmıdır veya yöntem ?

Örneğin dosya yolu
`C:\Musics`

**Comment by abdurrahmanekr** [comment]
Projenizin bulunduğu dizinden dosyayı açmanız gerekir. ör:
```
proje
    - music.mp3
    - index.html
    - index.js
```
bu projede `index.js` dosyasında bir mp3 çalmanız için şöyle bir yol belirtmelisiniz: `./music.mp3`
`C:/` veya `/var/www/html`gibi yollar sizin kişisel bilgisayarınızın absolute yollarıdır. O yüzden başka bir kişinin bilgisayarında bu yol çalışmayabilir.

**Comment by aozfen** [comment]
Zaten kullanıcı kendi bilgisayarından açacak ses dosyasını bunun için hangi yolu izlemeliyim ?

**Comment by abdurrahmanekr** [comment]
Eğer bilgisayarın bir dosyasını açmak veya görüntülemek istiyorsanız yolun başında `file://` eklemelisiniz.

**Comment by aozfen** [comment]
`file:///C:/Users/ahmet/Desktop/a.mp3` 

bunun gibi ? yine hata aldım

**Comment by aozfen** [comment]
Not allowed to load local resource: file:///C:/Users/ahmet/Desktop/a.mp3
Uncaught (in promise) DOMException: Failed to load because no supported source was found.


bu iki hatayı alıyorum

**Comment by abdurrahmanekr** [comment]
Tıpkı hatada verdiği gibi "Not allowed to load local resource, yerel kaynaklardan dosya yüklemeye izin yok". Şöyle düşünün, bir siteye giriyorsunuz ve sizin yerel dosyalarınıza erişiyor. Bu durum bir gizlilik sorunu. Eğer kullanıcının yerel dosyalarda müzik çalmasını istiyorsanız ilk önce o dosyaları kullanıcının yüklemesini isteyin sonra yükledikten sonra zaten çalabilirsiniz.

**Comment by aozfen** [comment]
Anladım teşekkür ederim. Bir çok yeri araştırdım fakat bu konuda bir çözüm yok. Birşey daha sorucam ses dosyasını veyahut müzik dosyasını kullanıcıdan alıp sunucuya yükletsem ve oradan çaldırsam, yüklediği müzikler için telif felan yeme durumu olur mu ?

**Comment by abdurrahmanekr** [comment]
sunucuya yüklemeden local'de çaldırabilirsiniz bu da telif hakkını ortadan kaldırır. Ama sunucuda barındırırsanız kullanıcıya gizlilik sözleşmesinde bundan bahsetmelisiniz.

**Comment by aozfen** [comment]
sunucuya yüklemeden nasıl çaldıra bilirim asıl araştırdığım kısım bu ?
