### ISSUE TITLE
ekran tasarımı

### ISSUE THREAD

**Issue by HacerBusraKILIC** [abdurrahmanekr/bana-istedigini-sor#35]
![ekran alintisi](https://user-images.githubusercontent.com/26281251/35884054-63b88a2e-0b9a-11e8-8ec2-10c1003eaff9.PNG)
 buradaki ekran ortasında artı şeklinde bulunan çizgi kullanmak istiyorum. ract-native de bunu nasıl sağlayabilirm.

**Comment by abdurrahmanekr** [comment]
Merhaba, Bu tasarımda 4 tane `View` oluşturmuş her birine de border verilerek yapılmış, basit bir şekilde söyle olur:
```javascript
<View
    style={{ flex: 1, flexDirection: 'column' }}>
    <View
        style={{ flex: 1 }}>
        İçerik1...
    </View>
    <View
        style={{ flex: 1, borderLeftWidth: 1, borderColor: '#ccc' }}>
        İçerik2...
    </View>
</View>

<View
    style={{ flex: 1, flexDirection: 'column' }}>
    <View
        style={{ flex: 1 }}>
        İçerik3...
    </View>
    <View
        style={{ flex: 1, borderLeftWidth: 1, borderColor: '#ccc' }}>
        İçerik4...
    </View>
</View>
```
Bunu daha da geliştirebilirsiniz.

**Comment by HacerBusraKILIC** [comment]
Teşekkür ederim.
