### ISSUE TITLE
Hata 

### ISSUE THREAD

**Issue by HacerBusraKILIC** [abdurrahmanekr/bana-istedigini-sor#36]
![image](https://user-images.githubusercontent.com/26281251/36060991-b3c8fa36-0e64-11e8-8016-9dd3b4892d98.png)

Github dan clone ladığım bir uygulamayı çalıştırmaya çalışırken bu hatayla karşılaşıyorum. Nasıl halledebilirim bir fikriniz var mı?

**Comment by abdurrahmanekr** [comment]
CardStackTransitioner.js dosyasının 66. satırında undefined bir nesnenin olmayan method'u çalıştırılmış. GitHub üzerinden kullandığınız projenin issue listesinde böylesi sorunları aratabilirsiniz. Böylesi hatalar ile çoğunlukla karşılaşabilirsiniz. İlk önce hatanın kaynağını bulun (yani gösterdiği dosyayı satırı) sonra buna dair kaynakları aratın muhtemelen birkaç issue ile karşılaşırsınız. Eğer böyle birşey ile karşılaşan olmamışsa o projeye issue açabilsiniz. Ben eğer bir kaynak ile karşılaşamazsam o hatayı kendim çözüp o projeye Pull Request açıyorum.

**Comment by HacerBusraKILIC** [comment]
Teşekkürler

**Comment by HacerBusraKILIC** [comment]
CardStackTransitioner.js böyle bir dosya görünmüyor.
