### ISSUE TITLE
react-native apk size

### ISSUE THREAD

**Issue by akserhat** [abdurrahmanekr/bana-istedigini-sor#40]
merhaba, uygulamam tamamlandıktan sonra apk oluşturdum ve 8 mb oldu. Görsel olarak 200mb dosya var. Bu kadar fazla olmasının sebebi ne acaba ?
sizin bir uygulamanızda bibilgi uygulaması 5mb store yükledikten sonra mı bu kadar düştü boyutu acaba?

**Comment by abdurrahmanekr** [comment]
Sanırsam BiBilgi uygulaması store üzerinde ionic olarak kaldı. O yüzden boyutu farklı görünebilir. Uygulamanın boyutunu daha çok kullanılan native bağımlılıklar etkiliyor. Resimlerin çok fazla etki yaptığını düşünmüyorum. İsterseniz [buraya](https://github.com/facebook/react-native/issues/5037#issuecomment-223758335) göz atabilirsiniz

**Comment by akserhat** [comment]
Teşekkür ederim  verdiğiniz linkte güzel açıklamış. 5 mb oldu uyglama :)
