### ISSUE TITLE
Developer Modu Kapatma

### ISSUE THREAD

**Issue by MuhammetAdamoglu** [abdurrahmanekr/bana-istedigini-sor#43]
Merhabalar, react native ile proje geliştirmekteyim ve genellikle sizi takip etmekteyim. Projemi tamamladım ancak geliştirici modundan çıkamadım, telefonu sallayınca karşıma dev menü geliyor veya could not connect hatası alıyorum.  Bunları nasıl kapatıp uygulamayı hazır hale getiririm. Saygılar

**Comment by abdurrahmanekr** [comment]
Telefonu sallayınca dediğinize göre ios için diyorsunuz.En basit şekliyle bu komutla yapabilirsiniz:
```
react-native run-ios --configuration Release
```
Olmadıysa 

XCode üzerinden projeyi açıp Product → Scheme → Edit Scheme ekranından
![](https://facebook.github.io/react-native/docs/assets/ConfigureReleaseScheme.png)
Build Configuration değerini release yapın.
ardından  AppDelegate.m dosyasındaki jsCodeLocation değerini şununla değiştirin (derleme aşamasında bu  main.jsbundle dosyası olşumuştur onu xcode'a referans etmelisiniz):
```
jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
```
Eğer  main.jsbundle dosyasını oluşturamadıysanız buraya göz atın: https://medium.com/react-native-development/deploying-a-react-native-app-for-ios-pt-1-a79dfd15acb8

Daha detaylı bilgi istiyorsanız [dokümanından](https://facebook.github.io/react-native/docs/running-on-device.html) faydalanmanızı öneriyorum. İyi çalışmalar

**Comment by MuhammetAdamoglu** [comment]
Aslında android için soruyordum, sallama olayı android de de var,eksik
bilgi verdiğim için kusura bakmayın.

react-native run-android --configuration Release kodu işe yararmı?



2018-04-09 19:35 GMT+03:00 Avare Kodcu <notifications@github.com>:

**Comment by abdurrahmanekr** [comment]
Hayır onun komutu farklı. Size belirttiğim dokümandan aldım bende orada da dediği gibi android için şu komutu çalıştırmalısınız:
```
react-native run-android --variant=release
```
Eğer o da olmazsa şöyle yapabilirsiniz:
```
cd android && ./gradlew assembleRelease
```

**Comment by MuhammetAdamoglu** [comment]
android için denediğimde unknow option '--configuration' hatası aldım


9 Nis 2018 Pzt 19:39 tarihinde muhammet adamoglu <muhammetadamoglu@gmail.com>
şunu yazdı:

**Comment by MuhammetAdamoglu** [comment]
bu kodu denemiştim ama sürekli bu hatayı alıyorum

9 Nis 2018 Pzt 19:42 tarihinde Avare Kodcu <notifications@github.com> şunu
yazdı:

**Comment by abdurrahmanekr** [comment]
Aldığınız hatayı göremiyorum

**Comment by MuhammetAdamoglu** [comment]
* What went wrong:
Task 'installRelease' not found in root project 'AwesomeProject'. Some
candidates are: 'uninstallRelease'.

9 Nisan 2018 19:53 tarihinde Avare Kodcu <notifications@github.com> yazdı:

**Comment by abdurrahmanekr** [comment]
Hmm, bir keystore dosyası oluşturmalısınız ve bunu gradle.properties dosyasında belirtmelisiniz. Bu tür adımları [buradan](https://facebook.github.io/react-native/docs/signed-apk-android.html) öğrenebilirsiniz.

**Comment by MuhammetAdamoglu** [comment]
Bugün app-release.apk yı çıkarttım, develop modundan çıktı yani. Her şey
için çok teşekkür ederim. Saygılar..


9 Nisan 2018 21:14 tarihinde Avare Kodcu <notifications@github.com> yazdı:

**Comment by abdurrahmanekr** [comment]
Sorununuzu çözdüğünüz için sevindim. İyi çalışmalar :)
