### ISSUE TITLE
"index.android.bundle"

### ISSUE THREAD

**Issue by HacerBusraKILIC** [abdurrahmanekr/bana-istedigini-sor#45]
![ekran alintisi](https://user-images.githubusercontent.com/26281251/39240473-86fe7564-488c-11e8-87f8-edbd8b3a259d.PNG)
 
Bu hatayı araştırdım ama çözümlerin hiçbiri işe yaramadı. Hiç karşılaştınız mı veya bilginiz var mı?

**Comment by abdurrahmanekr** [comment]
[Buradaki](https://stackoverflow.com/a/44476757/5769352) yöntemi denediniz mi?

**Comment by HacerBusraKILIC** [comment]
Evet bu sorunu halletti. Teşekkür ederim.
