### ISSUE TITLE
A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by HacerBusraKILIC** [abdurrahmanekr/bana-istedigini-sor#46]
![ekran alintisi1](https://user-images.githubusercontent.com/26281251/39244257-df739a4c-4898-11e8-9446-63132d820308.PNG)
![image](https://user-images.githubusercontent.com/26281251/39244288-f239294e-4898-11e8-9bfb-e0e4fc88abc4.png)

Bu hata için bir bilginiz var mı?

**Comment by abdurrahmanekr** [comment]
Peki bu biraz önceki yazdığınız kodun üzerine olan bir sorun mu?

**Comment by HacerBusraKILIC** [comment]
Hayır. Bu projede bu hatayı aldım. Sonra başka bir projede de "index.android.bundle" hatası oluştuğunu farkettim. Yani ikisi ayrı projelerdeki hatalar.

**Comment by abdurrahmanekr** [comment]
Hmm. `react-native run-android --info`komutunu çalıştırıp oluşan hatayı tekrar atar mısınız?

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/39245823-78abf692-489d-11e8-8419-670ab89784de.png)

**Comment by abdurrahmanekr** [comment]
Garip :/ `cd android` ile android dizinine geçip şöyle dener misiniz?
`./gradlew assemble --info`

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/39246103-42f84ae0-489e-11e8-99b1-cf563647cd39.png)

**Comment by abdurrahmanekr** [comment]
Sanırsam sorun react-native-vector-icons bağımlılığından kaynaklanıyor. Tekrar kurmak için ana dizine geri dönüp şu komutu çalıştırır mısınız?
`npm i react-native-vector-icons --save`

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/39248018-acbb6e58-48a3-11e8-8211-416f04ff5ebc.png)

**Comment by abdurrahmanekr** [comment]
Rica ederim, sorunu çözdüğünüze sevindim. En son işlemi yaparken react-native-vector-icons kullanıyordu ve orada hata vermişti, oradan anladım. Ben bu sorunu çoğu kez yaşadım. Sadece bu bağımlılıkta değil tabii ki. Bu tür durumlarda --info kullanıyorum ve sorunun hangi bağımlılıktan kaynaklandığını buluyorum.  İyi çalışmalar :)
