### ISSUE TITLE
Cihazda "index.android.bundle"

### ISSUE THREAD

**Issue by HacerBusraKILIC** [abdurrahmanekr/bana-istedigini-sor#47]
![39240473-86fe7564-488c-11e8-87f8-edbd8b3a259d](https://user-images.githubusercontent.com/26281251/39395863-c2401d78-4aec-11e8-9a03-9e087ede292b.png)

Emülatör üzerinde çalıyor ama cihazda bu hatayı veriyor.

**Comment by abdurrahmanekr** [comment]
Eğer development olarak derlemişseniz bunun için telefonu sallayın ve Dev Settings > Debug server host & port for device seçeneğine basın ve bilgisayarınızı ip'sini yazın (tabi bilgisayarınızda npm start ile projeyi yayına açmanız gerekiyor)

**Comment by HacerBusraKILIC** [comment]
C:\Users\dell\AppData\Local\Android\sdk\platform-tools dizininde
 "adb reverse tcp:8081 tcp:8081" 
"adb start-server"
ve proje dizininde react-native start yaptım. Bu şekilde çözüldü.

**Comment by abdurrahmanekr** [comment]
Bu yöntemi bilmiyordum. Ben genellikle telefonda yapıyorum bunu. Sorun çözüldüyse kapatıyorum
