### ISSUE TITLE
"RNGADBannerView does not exist" error hakkında

### ISSUE THREAD

**Issue by krkmzugur** [abdurrahmanekr/bana-istedigini-sor#49]
Merhabalar;

İki gündür admob reklamlarını hazır olan navigation eklentili projeye dahil etmek istememe rağmen bir türlü olmadı. Basit bir proje  oluşturarak eklemeye çalıştım. Olmadı. Bakarsanız sevinirim.

https://facebook.github.io/react-native/docs/linking-libraries-ios.html#content 

Buradaki birinci adımı atlıyorum sanırım. Ne yazmalıyım buraya bilemedim.

Saygılar.

**Comment by krkmzugur** [comment]
Admob eklemek bu kadar sıkıntılı olmamalı diye düşünüyorum.

**Comment by abdurrahmanekr** [comment]
Merhaba, `react-native link react-native-admob` komutunu çalıştırdınız mı?

**Comment by krkmzugur** [comment]
Evet hocam denedim. react native link diyordum sadece şimdi denedim yine aynı hata.

**Comment by abdurrahmanekr** [comment]
Bunun kurulumu hakkında [bir yazı](http://www.avarekodcu.com/konu/27/react-native-reklam-yerlestirme-ve-google-admob-kullanimi) yazmıştım. Oradaki adımları sırasıyla yapıp dener misiniz?

**Comment by abdurrahmanekr** [comment]
Veya [çalışan örneği](https://github.com/abdurrahmanekr/react-native-admob-example)nden bakabilirsiniz

**Comment by krkmzugur** [comment]
Uygulama adımlarını tek tek denedim hocam. Olmadı. Çalışan örneği indirip Android Studio içinde açtığımda build edilemediğinden o  örnekte kaldı. 

Kütüphaneyi dahil edip, kodu çalıştırıyorum. Sizden ricam. Siz boş bir projeye ekleyip deneyebilir misiniz. ? 

```
export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
   
        <Text>
        <AdMobBanner
          adSize="fullBanner"
          adUnitID="ca-app-pub-3940256099942544/6300978111"
          testDevices={[AdMobBanner.simulatorId]}
          onAdFailedToLoad={error => console.error(error)}
        />
        </Text>
      </View>
    );
  }
}
```

**Comment by abdurrahmanekr** [comment]
Programı kendiniz çalıştırmalısınız. Android studio içinde değil, komut satırında bu işi halletmeniz gerekir. `react-native run-android` veya android dizinine geçip `./gradlew assemble` komutu ile derleme yaptınız mı?

**Comment by krkmzugur** [comment]
Android Studio ile bir defeya mahsus genymotion içerisinde uygulama ikonu düşsün diye çalıştırıyorum. Sonrasında react-native run-android ile ekrandaki hata ile karşılaşıyorum. Metro Bundler sıkıntısız çalışıyor.

**Comment by abdurrahmanekr** [comment]
Ben attığım örneği kendi bilgisayarımda çalıştırdım. Yaptığım adım şunlar:

- git clone https://github.com/abdurrahmanekr/react-native-admob-example
- cd react-native-admob-example
- npm install
- react-native run-android

Ve başarılı bir şekilde Genymotion üzerinde uygulamayı açabildi. Bu kadar sorunun çıkmaması gerekiyor.

**Comment by krkmzugur** [comment]
Android Studio güncellenerek sorun aşılmıştır hocam. Teşekkürler.
