### ISSUE TITLE
react-native-camera CameraManager.Aspect hatası Çözümü

### ISSUE THREAD

**Issue by ahmetozalp** [abdurrahmanekr/bana-istedigini-sor#5]
Merhaba react-native camera ozleligini aktif edip ekrana vercem ama surekli hata basıyor ekrana uygulama

<img width="395" alt="if7j40" src="https://cloud.githubusercontent.com/assets/15075759/24161101/2f13cf08-0e6c-11e7-8c85-7395b5f36115.png">

**Comment by abdurrahmanekr** [comment]
Kamera ya izin verin mi info.list dosyasında daha önce camera kullanmadım kullandığın proje nedir ?

**Comment by ahmetozalp** [comment]
dur paylaşıyım github dan bi bak projeye

**Comment by ahmetozalp** [comment]
https://github.com/ahmetozalp/react-native-camera-problem yüklenıyor şuan semn gordugunde yüklenmiş olcak buyuk ihtimal bi bakabilirmisin 


masaustune indirdikden sonra 

npm install -g react-native-camera --save
npm install -g react-native-vector-icons --save


package.json camera kurulum satırı:

"react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git"

yap camera surumleri ile biraz oynadım

**Comment by abdurrahmanekr** [comment]
<img width="354" alt="ekran resmi 2017-03-20 os 12 58 20" src="https://cloud.githubusercontent.com/assets/15075759/24095223/c3c2c18a-0d64-11e7-9ec8-480e96929def.png">
Bağımlılık hatası alıyorum

**Comment by ahmetozalp** [comment]
ios da denedin dogrumudur? bende bu şekılde hata vermiyor da

**Comment by abdurrahmanekr** [comment]
Projeyi sen package.json ekler misin birde baştan benim gibi kursana çalışıyorsa tekrar deneyeceğim

**Comment by ahmetozalp** [comment]
https://github.com/ahmetozalp/react-native-camera-problem/blob/master/package.json

buyur

**Comment by ahmetozalp** [comment]
sen nasıl kurdun kı ?

**Comment by ahmetozalp** [comment]
yardım etcen mı? saat başıcevap yazdın mı diye bakıyorumda

**Comment by abdurrahmanekr** [comment]
@ahmetozalp mail gelmesi gerekir ben yazdığımda beklemene gerek yok gibi. İşten başımı alabilsem 😄 bakacam 😃

**Comment by abdurrahmanekr** [comment]
@ahmetozalp ben şu anda ben android'de denedim oradaki adımları denedim çalıştı sen react-native link diyerek denedin mi ? repository'nin issue bölümünde hiç arrattın mı ? ben arattığımda [bir çok issue var bu konuda](https://github.com/lwansbrough/react-native-camera/issues?utf8=%E2%9C%93&q=CameraManager.Aspect) Ben gittiğim adımları yazayım 
1. İlk önce react native yüksettim package.json şu halde:
```
{
  "name": "StorySharing",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.4.0",
    "react-native": "^0.40.0",
    "react-native-camera": "git+https://github.com/lwansbrough/react-native-camera.git",
    "react-native-vector-icons": "^2.0.3"
  }
}
```
2.  node_modules klasörünü sildim (ios'da build dosyasını silmeni öneririm)
3. `npm install`
4. `react-native link` kütüphaneler dahil ettim (burası önemli sorun bu yüzden oluyor olabilir)
5. `react-native run-android` veya `react-native run-ios`
6. uygulama çalıştı yalnız dikkatimi çeken bir yer oldu orayıda düzelttim `index.ios.js` dosyasında
```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View
} from 'react-native';
import StorySharing from './app/containers/app';


AppRegistry.registerComponent('StorySharing', () => StorySharing);
```
StorySharing yerine SnapChat vardı uygulama sende nasıl açıldı hâla hayret ediyorum :confused: 
7. ![ekran goruntusu 2017-03-21 20 12 16](https://cloud.githubusercontent.com/assets/15075759/24160400/5d007d78-0e6a-11e7-8632-e5c10fc32216.png) bende çalıştı tabi plugin simulator üzerinde sadece text gösteriyor.
Eğer hala bir sorun oluyorsa yine yazabilirsin. Ben sürekli olarak open source katkı sağlayamıyorum. mâlum çalışıyorum bu yüzden benim cevaplarımı beklemek yerine e-posta bildirimlerini açabilirsin. Zaten  bir yorum eklediğimde sana push mail düşer. Ne kadar istesemde elimde değil :confused: Bu arada başlığı değiştirmem gerekiyor başka insanlarda bu sorun çıkabilir.

**Comment by ahmetozalp** [comment]
Yardımın için teşşekurler oncelikle bu sefer de şöyle bir hata geldi :) 


http://imgur.com/a/Uo68X

**Comment by ahmetozalp** [comment]
teşşekurler fixledim

**Comment by abdurrahmanekr** [comment]
Çözümünü anlatirsan başkalarına faydan dokunur :smile:

**Comment by ahmetozalp** [comment]
Kamera modulunun ios için xcode uzerinde 1-2 ayarı var kutupanede dosya ekleme gibi internette rahatlıklı modulu kurdukdan sonrakı ayarlara bakabilirler bu olay ios için.
