### ISSUE TITLE
Shortcode add do action 

### ISSUE THREAD

**Issue by muratdesign** [abdurrahmanekr/bana-istedigini-sor#50]

**Comment by abdurrahmanekr** [comment]
Bu konuyu, anlamadığım için kapatıyorum. Sorunuzu Türkçe sorabilirsiniz. Önceden yanıtlamış olduğum soruları görmek için [burayı](https://github.com/abdurrahmanekr/bana-istedigini-sor/issues) kullanabilirsiniz. İyi çalışmalar.
