### ISSUE TITLE
'node_modules' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by HacerBusraKILIC** [abdurrahmanekr/bana-istedigini-sor#51]
![image](https://user-images.githubusercontent.com/26281251/40354642-07d9b99c-5dbd-11e8-8087-0990c44cdcf0.png)

Bu hataya karşı ne yapabilirim?

**Comment by abdurrahmanekr** [comment]
Merhabalar, soruyu başta görmüştüm fakat o an başka bir yere odaklanınca sizin sorunuzu cevaplamayı unuttum :( kusuruma bakmayın.

Sorun çözüldü mü?

**Comment by HacerBusraKILIC** [comment]
Sorun değil :) Çözememiştim ama şuan sınavlarım var bu tarafla ilgilenemiyorum. Tekrar baktığımda sorumu yenileyebilirim.

**Comment by abdurrahmanekr** [comment]
package.json dosyasında ne yazıyor onu paylaşabilir misiniz?

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/40735649-61b2e924-6444-11e8-92e7-9ac3d604744c.png)

 **backend klasörü içindeki package.json dosyasını  paylaşıyorum**

![image](https://user-images.githubusercontent.com/26281251/40735709-90e55380-6444-11e8-9bc9-0591181c3332.png)

**Comment by abdurrahmanekr** [comment]
Hmm scripts nesnesinin içindeki start betiğinde bazı düzenlemeler yapmak gerekiyor. node_modules/ şeklide giden ifadelerin soluna `./` ekleyip dener misiniz? ör: 
```
./node_modules/nodemon/bin/nodemon.js
```

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/40742255-9957428c-6456-11e8-961b-1d3da4239779.png)

**Comment by abdurrahmanekr** [comment]
Hmm şunu dener misiniz:
```
nodemon -- babel-node server.js
```

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/40743264-b2aff92e-6459-11e8-8503-a8b3c97d0e75.png)

bir yerde daha takıldı. Peki ne yaptık burada anlatabilir misiniz?

**Comment by abdurrahmanekr** [comment]
Şimdi açıkçası ben de tam olarak nodemon işleminin ne yaptığını bilmiyorum. Amacım komut dosyasını çalıştırabilmekti. Zaten verdiği hatada "node_modules komutu tanınmıyor" şeklindeydi. eğer kurmuş olduğunuz bir paket, script komutu içeriyorsa "node_modules/.bin/komut .." şeklinde çağırmanıza gerek kalmıyor. Çünkü onu npm zaten otomatik bulduğu için sadece "komut .." şeklinde yazmanız yeterli oluyor. 

Aslında başardık.

Sonradan verdiği hata büyük ihtimal nodemon kullanımı ile alakalı. nodemon işlemini doğru kullandığınıza emin olmalısınız. Verdiği hata zaten 

```
node babel-node server.js
```
komutunu çalıştıramadığından kaynaklanıyor. `node` nodejs komutu bir sonraki parametre ise çalıştıracağı dosya ama sizin dizininizde babel-node dosyasını bulamadığı için normal olarak hata veriyor.
