### ISSUE TITLE
(React-Native)  Web service

### ISSUE THREAD

**Issue by kerimdemir** [abdurrahmanekr/bana-istedigini-sor#52]
Merhabalar @abdurrahmanekr,  

 Web servisten dönen veriyi, uygulama içinde kaydedip tab menude sayfalar arası geçiş yaparken tekrardan servise çıkılmasın istiyorum.Bunu ne şekilde yapabilirim, Teşekkürler.

Örnek:
![videotogif_2018 06 04_14 50 49](https://user-images.githubusercontent.com/19932626/40916469-811d8540-6808-11e8-8740-30359a981707.gif)

**Comment by abdurrahmanekr** [comment]
Kullandığınız tabs kütüphanesinde onSwipe gibi bir event varsa ona bağlayabilirsiniz.
