### ISSUE TITLE
React native animations

### ISSUE THREAD

**Issue by chelenli** [abdurrahmanekr/bana-istedigini-sor#53]
Selamlar, arka plandaki resmi büyütme animasyonu yapmak istiyorum ama ona bağlı text vb subview ler de aynı animasyonu yapıyor, onlar da büyüyor. Bunu nasıl engelleyebilirim

**Comment by abdurrahmanekr** [comment]
Merhaba, resme child component vermeyin içine koymak istediğiniz elementleri imageden sonra ekleyin. Şöyle bir şey yani:

```javascript
<View>
    <View> // animasyon yapılacak view
        <Image ...>
    </View>
    <View>
        diğerleri
    </View>
</View>
```
Bunun için resmi absolute yapmanız gerekiyor. position:'absolute', width: "100%", height: "100%" şeklinde olabilir.

**Comment by chelenli** [comment]
Çok teşekkür hızlı dönüşünüz için 👍 İşe yaradı
