### ISSUE TITLE
Execution failed for task ':app:processDebugGoogleServices'.

### ISSUE THREAD

**Issue by HacerBusraKILIC** [abdurrahmanekr/bana-istedigini-sor#56]
![image](https://user-images.githubusercontent.com/26281251/42732932-df54126a-8832-11e8-9c3c-81f1a5ddf9a8.png)

firebase de facebook ile giriş yapmak için çalışıyordum. Bu hatayı nasıl çözebilirim?

**Comment by abdurrahmanekr** [comment]
SDK manager üzerinden SDK Tools içinde **Google Repository** kurulu mu sizde?

![ekran resmi 2018-07-15 os 1 32 16](https://user-images.githubusercontent.com/15075759/42732995-84bbc680-8833-11e8-87bc-d6d0acbdf04e.png)

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733054-f2b50f5c-8833-11e8-8a7f-28f098eec4b7.png)
 evet kurulu

**Comment by abdurrahmanekr** [comment]
denediğiniz topluluktan baktığınız çözümler var mı?

**Comment by HacerBusraKILIC** [comment]
https://stackoverflow.com/questions/34990479/no-matching-client-found-for-package-name-google-analytics-multiple-productf
buradakiler işe yaramadı

**Comment by abdurrahmanekr** [comment]
android/build.gradle dosyasına google-services eklediniz mi?
```diff
  dependencies {
    classpath 'com.android.tools.build:gradle:2.0.0'
+   classpath 'com.google.gms:google-services:3.0.0'
```

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733178-87d83a4a-8835-11e8-818e-4ed6751e5639.png)

evet ekledim

**Comment by abdurrahmanekr** [comment]
peki android/app/build.gradle dosyasının içine bunu eklediniz mi
```
apply plugin: 'com.google.gms.google-services'
```

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733201-dc24b42a-8835-11e8-87fd-57dc28e24bcc.png)
 evet ekledim

**Comment by abdurrahmanekr** [comment]
onu en alta taşıyıp dener misiniz?

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733224-3cd75ade-8836-11e8-9883-7f7be28dafcb.png)
 aynı hatayı alıyorum

**Comment by abdurrahmanekr** [comment]
android dizininde şu komutu çalıştırıp deneyebilir misiniz?
```
./gradlew dependencies
```

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733257-00b1b1f2-8837-11e8-8ac8-c20685721dfb.png)

![image](https://user-images.githubusercontent.com/26281251/42733276-4fa7088e-8837-11e8-947a-119f01f30cf9.png)

**Comment by abdurrahmanekr** [comment]
E başardık o zaman :D 👍

**Comment by abdurrahmanekr** [comment]
success'i görünce sorun çözüldü sandım :/ herhalde android/app/google-services.json dosyasında bir bozukluk var

**Comment by HacerBusraKILIC** [comment]
Anladım çok teşekkürler.

**Comment by abdurrahmanekr** [comment]
@HacerBusraKILIC çözüldü mü?

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733351-b5c5df9a-8838-11e8-9f2c-a7ad79db1c50.png)
Burada görebildiğim bir bozukluk yok. malesef iki gündür bakıyorum ama hiç bir şey bulamadım

**Comment by abdurrahmanekr** [comment]
Sanırsam paket isminden kaynaklanan bir sorun var
google-services.json üzerinden tanımlanan isim `com.fbLoginWithFirebaseExample` iken uygulamanız `com.fbloginwithfirebaseexample` şeklinde isimlendirilmiş. Bunu düzeltmek için firebase üzerinden yeniden bir uygulama oluşturun ama local'inizde tanımladığınız isimde olmalı (yani `com.fbloginwithfirebaseexample`). Sonra o google-services.json dosyasını indirip tekrar deneyin bakalım olacak mı.

**Comment by HacerBusraKILIC** [comment]
Tamam bakıyorum

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733673-58ab5b90-883e-11e8-899a-9a5bf721e85f.png)

**Comment by abdurrahmanekr** [comment]
güzel en azından bir önceki sorun giderilmiş oldu. gradlew'in cache'ini silip tekrar dener misiniz?

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733756-cb60beb8-883f-11e8-945a-4d5240f1717c.png)

**Comment by HacerBusraKILIC** [comment]
![image](https://user-images.githubusercontent.com/26281251/42733783-4f81aa36-8840-11e8-97da-0f672065031c.png)

**Comment by sametcodes** [comment]
Gradle'ın yeni versiyonunda bazı anahtarlar değişti.

**build.gradle** içerisindeki
**compileOnly** anahtarını **provided**,
**implementation** anahtarını **compile** olarak değiştirmeyi deneyebilirsin.

https://github.com/abdurrahmanekr/bana-istedigini-sor/issues/56#issuecomment-405083167 burada da compile anahtarı için değiştirmeni gerektiğini söylemiş.

Eğer native bileşen kullanan modüllerin varsa, tüm **node_modules/*/android/build.gradle** dosyası için bu işlemi yapman gerekiyor. Tek tek aramana gerek yok, zaten herhangi birinde hata verirse hata kodu olarak hangi dosyada olduğunu söyleyecektir.

via: https://github.com/react-community/react-native-maps/issues/2188#issuecomment-385420099

**Comment by HacerBusraKILIC** [comment]
Teşekkürler. Dediklerinizde vardı en önemli nokta ise compileSdkVersion 27, buildToolsVersion "27.0.2" diye düzenleince çözüldü.

**Comment by abdurrahmanekr** [comment]
Teşekkürler aziz dostum @selmansamet 👍
