### ISSUE TITLE
Execution failed for task ':app:processDebugGoogleServices'.

### ISSUE THREAD

**Issue by HacerBusraKILIC** [abdurrahmanekr/bana-istedigini-sor#57]
![image](https://user-images.githubusercontent.com/26281251/42733295-9d2cc850-8837-11e8-9c98-153eb1c231cf.png)

Kusura bakkmayın ama hata devam ediyor.

**Comment by abdurrahmanekr** [comment]
yoruma hızlı cevap verince kapattım buradan devam edebiliriz #56
