### ISSUE TITLE
React native login hk.

### ISSUE THREAD

**Issue by yusufcelik72** [abdurrahmanekr/bana-istedigini-sor#58]
Merhabalar,

aşağıdaki linkte bulunan login template'i kullanmak istiyorum fakat, sizin videodaki durumun aksine button ve inputlar farklı js dosyalarında. butona tıklandığında input valuelarına nasıl ulaşabilirim?

Teşekkürler. 

https://github.com/dwicao/react-native-login-screen

**Comment by abdurrahmanekr** [comment]
React'in [props](https://reactjs.org/docs/components-and-props.html) özelliğini kullanabilirsiniz. O view'ı oluşturan component'e bir özellik vererek çağrıldığı yere kadar götürebilirsiniz. Örnek olarak:

```javascript
class BenimInput extends Component {
    render() {
        return (
            <View>
                <TextInput
                    onChangeText={this.props.onChangeText}/>
            </View>
        );
    }
}

class CagiranView extends Component {
    render() {
        return (
            <View>
                <BenimInput
                    onChangeText={() => {
                        // yazı girildiğinde burası çalışacaktır
                    }}/>
            </View>
        )
    }
}
```
