### ISSUE TITLE
Otomatik Websocket hatası (React-Native)

### ISSUE THREAD

**Issue by haciSeydaoglu** [abdurrahmanekr/bana-istedigini-sor#6]
Merhaba hocam. Bir konuda yardımınıza ihtiyacım var. React Native'de sizin login projenizde olduğu gibi fetch ile bir giriş yap formu yaptım. Sorun yok burada. Fakat aşağıdaki resimden de görebileceğiniz gibi network'ten bakınca websocket hatası çıkıyor. Sürekli kendi kendine bir websocket'e bağlanmaya çalışıyor. Bunun benim kodlarımla da bir alakası yok. Çünkü fetch'i kaldırınca da böyle yapıyor. Bu sorun şu anda bit engel oluşturmuyor benim içi. Fakat arka planda app'i yavaşlatmasından şüpheleniyorum.
Resim: 
![](http://i.hizliresim.com/qbyqmZ.png)

(Bu arada Genymotion ve React Native'in 4.3 sürümünü kullanıyorum.)
Yardımcı olursanız çok sevinirim. İyi çalışmalar dilerim.

**Comment by abdurrahmanekr** [comment]
Merhaba @haciSeydaoglu Aslında bunlar geliştirici modunda çalışıyor evet sen burada bir istek atmıyorsun. Uygulamayı release modda derlersen bu istekleri atmayacak. Bunun amacı zaten **live reloading** ve **hot reloading** yönetmek. Bir sıkıntı yok yani

**Comment by haciSeydaoglu** [comment]
Çok teşekkür ederim @abdurrahmanekr hocam. 2 gündür bütün aramalarıma rağmen bir sonuç buamamıştım. :)
