### ISSUE TITLE
React Native'de İki İsimli Paket init Etmek

### ISSUE THREAD

**Issue by ahmedfeyzi** [abdurrahmanekr/bana-istedigini-sor#61]
Selamun Aleyküm..

`com.organization.projectname` şeklinde projeyi nasıl init edebiliriz acep, tek isimli yani `com.organization` şeklinde init edip sonra proje dosyalarından paket ismini değiştirmek yöntemini yazmışlar stackoverflow da.. bunun ilk init aşamasında yapılabiliyor olması gerek diye düşünüyorum, fakat bulamadım.. Bu konu hakkında bilginiz varmı?

**Comment by abdurrahmanekr** [comment]
Ben de bir kod bulmuştum ama denediğimde tam da istediğimi yapamamıştı, o yüzden her yeri kendim değiştirmek zorunda kaldım.
