### ISSUE TITLE
React Native'de Uzun Yazılara Yer Ayracı Koymak

### ISSUE THREAD

**Issue by ahmedfeyzi** [abdurrahmanekr/bana-istedigini-sor#62]
Selamun Aleyküm..

Uygulama içerisinde okunacak uzun yazılara yer ayracı koyabilmek için nasıl bir yol izlenebilir, tavsiyenizi merak ediyorum..

Ben şu şekilde düşündüm ama bu sanki çok projesyonelce değil gibi.. Yer ayracı koyulmak istendiğinde ilk önce; yazı boyutunun da değiştirilmiş olmasına karşın yazı boyutunu sonrasında da Scroll değerini alıp kaydetmek..

**Comment by abdurrahmanekr** [comment]
Ve aleyküm selam.

Bence kişinin bulunduğu paragrafı bulan bir sistem kurabilirsiniz. paragraf bir dizi olur dizinin içinde de ayraç değeri olur, if ile onu bulduğunuzda listeye ayracı yapıştırırsınız.
