### ISSUE TITLE
BackHandler ve BackAndroid Debug Mod Dışında Çalışmıyor.

### ISSUE THREAD

**Issue by sercanyeniyurt** [abdurrahmanekr/bana-istedigini-sor#63]
Merhabalar,

react-native-router-flux kullanıyorum, emülatörde remote debug mod açıkken hardware geri buttonuna basınca aşağıdaki kod gayet sağlıklı çalışıyor, fakat debug moddan çıkınca emülatördeki geri tuşuna bastıgımda uygulamadan çıkıp arkaplana atıyor, çok araştırdım fakat sonuç elde edemedim, 

versiyonlar ;

RN 0.54
RNRF 3.0.2

Kodlarım şu şekilde;

const RouterComponent = () => {
    onBackPress = () => {
        console.log(Actions.state);
        if (Actions.state.index === 0) {
            return false;
        }
        Actions.pop();
        return true;
    };
    return (
        <Router createReducer={reducerCreate} backAndroidHandler={this.onBackPress}>
            <Stack key="root">
                <Scene key="loginScreen" component={LoginForm} title="Artel" initial  navBar={navbar1}/>
                <Scene key="setting" component={Settings} title={strings.route_1}   navBar={navbar1}/>
                <Drawer key="main" hideNavBar={true}  contentComponent={Menu} drawerWidth={200} drawerPosition={'right'}>
                    <Scene key="performance"  navBar={navbar2} component={Performance} title={strings.route_2} initial/>
                    <Scene key="machinedetails"  navBar={navbar2} component={MachineDetails} title={strings.route_3}/>
                    <Scene key="machinereport"  navBar={navbar2} component={MachineReports} title={strings.route_4}/>
                    <Scene key="persondetails"  navBar={navbar2} component={PersonDetails} title={strings.route_5}/>
                    <Scene key="personreports"  navBar={navbar2} component={PersonReports} title={strings.route_6}/>
                    <Scene key="planing"  navBar={navbar2} component={Planing} title={strings.route_7}/>
                    <Scene key="maintenance"  navBar={navbar2} component={Maintenance} title={strings.route_8}/>
                </Drawer>
            </Stack>
        </Router>
    );
};

**Comment by abdurrahmanekr** [comment]
Merhaba, daha önce böyle bir sorun ile karşılaşmadım. Uygulamayı bir de gerçek bir cihaz üzerinde deneyin isterseniz.
