### ISSUE TITLE
React native 

### ISSUE THREAD

**Issue by efendi7878** [abdurrahmanekr/bana-istedigini-sor#64]
Merhaba ,
Öncelikle teşekkür ederim. 
Ben react native uygulama yapmak istiyorum uygulama içi satın alma işlemi olacak, bununla alakalı detaylı bilgiyi bulamadım, yardımcı olurmusunuz ?

**Comment by abdurrahmanekr** [comment]
Merhaba [böyle bir kaynak](https://medium.com/@dooboolab/react-native-in-app-purchase-121622d26b67) belki yardımcınız olabilir. Daha önce RN üzerinde in-app purchase yapmadığım için yardımcı olamıyorum. Teşekkür ederim.
