### ISSUE TITLE
Sayfaya geri dönüldüğünde tekrar render yapmasın ?

### ISSUE THREAD

**Issue by sercanyeniyurt** [abdurrahmanekr/bana-istedigini-sor#65]
Merhabalalar,

Bir ekranımda veriler socket üzerinden sayfaya yüklenip render oluyor, fakat sayfayı değiştirip tekrar o sayfaya döndüğümde renderlama işlemi tekrar ediyor. ben tekrar render etsin istemiyorum ilk girildiğinde render edilen veriler görünsün istiyorum.

tekrar render ettiğinde işlem uzun sürüyor çünkü, bunu nasıl yapabilirim ?

**Comment by abdurrahmanekr** [comment]
Bunu shouldComponentUpdate kullanarak yapabilirsin. constructor methodu çalıştığında this.lock = false; olur. shouldComponentUpdate methodunda ise this.lock'u kontrol edip eğer false ise render etmesini sağlarsın render methodunda ise this.lock = true; verdiğin zaman render methodu çalışmaz duruma gelir. bunun dışında render methodunu çalışmasını sağlayan diğer yerlere de aynı şekilde kontrol eklemen gerekebilir. (ör: componentWillReceiveProps)
