### ISSUE TITLE
SQLite kullanamıyorum

### ISSUE THREAD

**Issue by aozfen** [abdurrahmanekr/bana-istedigini-sor#68]
``` 
SqlService.query("SELECT * FROM tbl_groups").then(res => {
    console.log(res)
});

```

Bu şekilde bir sorgu kullanıyorum loga hiç düşmüyor bile. Debugger ilede test ettim gelmıyor oraya.

``` 
SqlService.select("tbl_groups", "*", "", []).then(res => {
      console.log('select',res);
 });

```

Bunu kullandığımda boş array döndürüyor. Tablo ismini değiştirince böyle bir tablo bulunamadı dıye hata veriyor yani burada bir sıkıntı olmadıgını düşünüyorum ancak insert'i kullanıyorum yine boş döndürüyor. İnsert methodu olumlu oldu mu olmadı mı oda geriye bir şey döndürmüyor.

``` 
SqlService.insert("tbl_groups", ["name"], ["SQL NAME"]).then(res => {
      console.log('insert',res)
 });

```

ve sürekli "warning - exception while invoking a callback: {"code":0}" hatasını alıyorum.

Saatlerce araştırdım ama bir sonuç bulamadım. Yardımcı olur musun ?

**Comment by abdurrahmanekr** [comment]
Merhaba, websqlite'ın timeout özelliği var. Insert işleminin sonucunu eğer beklemek istiyorsanız `SqlService.rightNow().insert(...` şeklinde çalıştırırsanız olur. Eğer tek tek uğraşmak istemiyorsanız init ederken timeout değerine 0 verirseniz tüm callback'lar senkron şekilde gelir. ör:
```
SqlService.init({
    id: 'user', // db name
    dbObject: window, // database object eg: window.openDatabase
    timeout: 0
})
```

**Comment by aozfen** [comment]
Teşekkür ederim `rightNow()` işimi çözdü. Birde şunu sormak isterim sqlite dosyasını göremıyoruz daha öncede birisi sormuş kernelde tutuluyor demiştiniz. Dosya halinde göremiyorsak bile SQL sorgusu ile db'de olan tabloları nasıl göre biliriz ? Araştırdım ancak bir sonuç bulamadım

**Comment by aozfen** [comment]
Onu da şuan buldum;
`SELECT name FROM sqlite_master WHERE type='table' ORDER BY name`
