### ISSUE TITLE
React Native Json Api ile işlemler

### ISSUE THREAD

**Issue by mmutlusari** [abdurrahmanekr/bana-istedigini-sor#69]
Merhaba @abdurrahmanekr 

React Native Json Rest Api ile oluşturulmuş api dosyasından veriye çekme, okuma, yazma, değiştirme, silme aynı şekilde gelen veriye göre kullanıcı girişi, kullanıcı kaydı, kullanıcı girişi sonrası verileri ilişkilendirmeye dayalı yönlendireceğin bir anlatım  var mı ya da bunlar ile alakalı bir anlatım yapmayı düşünür müsün?

**Comment by abdurrahmanekr** [comment]
Merhaba @kutups, böyle bir anlatım gerçekten harika olurdu. Açıkçası çok takip edemiyorum belki yapan birisi vardır. Ancak böyle bir seri yapar mıyım orası kesin değil. Çünkü daha önce yapmaya çalıştığım satranç serisine çok ilgi gösterilmediği için durmak zorunda kaldım. Böyle bir seri yapacaksam büyük ihtimal uzun bir süre beklerim :/
