### ISSUE TITLE
Json ve Türkçe Karakter sorunu

### ISSUE THREAD

**Issue by gurhancoban** [abdurrahmanekr/bana-istedigini-sor#7]
Dün size JSON ile ilgili soru sormuştum EOF hatasının kaynağı MYSQL'de tuttuğum Türkçe karakterlerden kaynaklanıyormuş. Bir kaç yere baktım ve önerdiğkleri veritabanı karşılaştırmasını utf8_general_ci olarak yaptım lakin işe yaramadı. PHP kodunu şu şekle getirdim lakin oda işe yaramadı. 

echo json_encode($result,JSON_UNESCAPED_UNICODE);

react-native deki login.js'sayfasında olan fetch bloğundaki header kısmına 
'Content-Type': 'application/json; charset=UTF-8', bunu ekledim. Bu da durumu değiştirmedi.

sanırım react-native tarafında kaynaklanıyor Türkçe Karakter sorunu. ona çözüm arıyorum. Biliyorsan paylaşırsan sevinirim.

Edt: Çözdüm :) Database için hazır bir sınıf kullanmıştım. orada set_charset yapılmamış. onu yapınca düzeldi. belki başkasına da lazım olur diye burada bırakıyorum. :)

**Comment by abdurrahmanekr** [comment]
Sorununu çözdüğün için mutlu oldum :tada: . Paylaştığın için teşekkür ederim :+1: 

> [Sorunun linki](http://www.avarekodcu.com/konu/17/react-native-ornek-login-uygulamasi-3-ajax-kullanimi-istekler-ve-uyarilar)
