### ISSUE TITLE
AngularJS

### ISSUE THREAD

**Issue by cml4** [abdurrahmanekr/bana-istedigini-sor#71]
AngularJS ve PHP kullanımıyla select form elemanından id seçimi yaptığımda sayfa yenilemeden seçilen id'ye ait veritabanında bulunan veriler (isim,no gibi) otomatik olarak çekilerek sayfada gösterilsin istiyorum. Nasıl yapabilirim?

**Comment by abdurrahmanekr** [comment]
select option elementlerine event listener eklerseniz ve o listener içerisinde php url'ine istek atarsanız istediğinizi yapmış olursunuz. Örnek olarak select elementine onchange listener ekleyelim.
```
<select onchange="secim(this)">
    <option value='1'>1. id</option>
    <option value='2'>2. id</option>
    <option value='3'>3. id</option>
</select>
```

alt tarafta da select'e ait fonksiyonu tanımlarız
```
<script>
function secim(element) {
    var id = element.options[element.selectedIndex].value;


    // network isteği atılır
    // cevabı geldiğinde angularjs scope değişikliği ile view'a yansıtılır
}
</script>
```
