### ISSUE TITLE
fcm Tek Cihaz(Single Device) Alanını Göremiyorum

### ISSUE THREAD

**Issue by figencetin** [abdurrahmanekr/bana-istedigini-sor#73]
Merhaba , http://www.avarekodcu.com/konu/41/react-native-firebase-push-notification-kurulumu-ios-ve-android-icin  yazınızda ki adımları tek tek uyguladım. Android cihazım için token değerimi aldıktan sonra fcm de mesaj gönderme kısmına geldim fakat sadece kullanıcı segmenti ve konu alanı var hedef kısmında.O alanı neden göremiyorum acaba ve token değerini nasıl ne şekilde girebilirim?

**Comment by abdurrahmanekr** [comment]
@figencetin Sorunu nasıl çözdünüz?

**Comment by figencetin** [comment]
Hedef kısmından token alanını kaldırmışlar. Mesaj bilgilerini doldurduktan
sonra ikinci aşamada cihazda test et diye bi şey var oradan ekledim token
değerini ve o şekilde gönderdim

19 Şub 2019 Sal 21:18 tarihinde Avare Kodcu <notifications@github.com> şunu
yazdı:

**Comment by figencetin** [comment]
Size fcm hakkında kafama takılan bir iki soruyu buradan sorabilir miyim
acaba?

2 Mar 2019 Cmt 11:19 tarihinde Figen Çetin <cetinfigenn@gmail.com> şunu
yazdı:

**Comment by abdurrahmanekr** [comment]
Olur
