### ISSUE TITLE
React Native İos Derleme Hataları Hk.

### ISSUE THREAD

**Issue by EmreKorpe** [abdurrahmanekr/bana-istedigini-sor#75]
Merhaba Abdurrahman bey, react native de geliştirdiğim android tarafı tamamlanan bir uygulamam var ios ta çalıştırma gibi bir düşüncem yoktu aslında mac pc de yoktu esase :D ios tarafı da istenince imac pc de android projemi ios için de derlemek istedim fakat ios ta hiçbir tecrübem yok ve hatalar almaktan yola devam edemiyorum.Bağımlılıklardan kaynaklanıyor bu durum tahminim. Fikir danıştığım bir kişi bana aynı uygulamayı sadece ios için yeniden kopyala yapıştır ile oluştur dedi paketler den kaynaklanan hataları anlık çözersin diye bu işlem mantıklı mı? İos tarafı için bana yardımcı olabilir misiniz?

**Comment by abdurrahmanekr** [comment]
Merhaba yaşadığınız problemi bulamadığınız zaman veya çıkmaz bir durumda hatayı bana danışabilirsiniz ama projenizle kişisel olarak ilgilenemem malesef. İyi çalışmalar.

**Comment by EmreKorpe** [comment]
Cevabınız için teşekkür ederim bu issue üzerinden sorarım o zaman abdurrahman bey. Şu konuda ne önerirsiniz uygulamayı ios için tekrar mı oluşturmalıyım android tarafında en az 15-20 bağımlılık yüklü ios tarafı ve android tarafını tek projede iki platforma da derlemek şu an için biraz zor bu yüzden ikisini de ayrı projeler de yürütme fikri almıştım bu konuda düşüncenizi öürenebilir miyim?

Şu anda derlemeye çalıştığım da aldığım hatayı paylaşıyorum ilginiz için teşekkür ederim

![IMG_8535](https://user-images.githubusercontent.com/16029286/55161487-b23f6280-5176-11e9-84a7-dcc4a8e38ed1.JPG)

**Comment by abdurrahmanekr** [comment]
Sanırsam android uygulamasına link edilen değişiklik ios'a yapılmamış görünüyor. Bu komutu çalıştırıp deneyin
```
react-native link
```
