### ISSUE TITLE
WildEmitter setState is not a function

### ISSUE THREAD

**Issue by srhtylmz19** [abdurrahmanekr/bana-istedigini-sor#78]
Hocam yazınızdan yararlanarak WildEmitter kullandım ve custom headerdaki textinput a materialTopTabBar sayfasında eriştim ve girilen değeri aldım ancak setstate yapmak istediğimde setState is not a function uyarısı veriyo yardımcı olabilir misiniz

**Comment by abdurrahmanekr** [comment]
“This binding” yapmıyor olabilirsiniz. [bkz](https://gist.github.com/zcaceres/2a4ac91f9f42ec0ef9cd0d18e4e71262)

**Comment by srhtylmz19** [comment]
yapıyodum hocam da , çözdüm sonradan. Teşekkür ederim @abdurrahmanekr
