### ISSUE TITLE
Genel Bilgi

### ISSUE THREAD

**Issue by hulusimizrak** [abdurrahmanekr/bana-istedigini-sor#8]
Merhabalar üstad,
- Tek platformda yazıp iki platformda (android,ios) çıktı alabiliyor muyuz ?
- Web service ile veri çekme,gönderme videosu çekecek misiniz ?
Şimdiden teşekkürler :)

**Comment by abdurrahmanekr** [comment]
Merhaba @hulusimizrak,
1. Sorunun cevabı: Tek platformda yazmak derken sadece bir tanesi üzerinde çalışmak sonra vakti gelince diğer platform'a derlemek diyorsan. Bunu yapabilirsin, **ama** normalde ios ve android birbirlerinin **tamamen** bütün özellikleri desteklemiyor. Yani doküman üzerinde bir nesne kullanacaksan orada bunun android için veya ios için desteklendiğine bakman gerekir. 3. parti plugin kuracaksan kurduğun plugin'in ios ve android için desteklendiğine bakman gerekir. Yani uygulama içinde bazı noktalarda platform bağımlılığı çıkabilir. Ona göre kontrollerini yapman gerekir.

2. Bu konu [blogumdaki bir konu](http://www.avarekodcu.com/konu/17/react-native-ornek-login-uygulamasi-3-ajax-kullanimi-istekler-ve-uyarilar)da bulabilirsin aynı zamanda [videosu](https://www.youtube.com/watch?v=lqIbuArJpTY) da var.

Umarım sorunlarına çözüm bulmuşumdur 😄

**Comment by hulusimizrak** [comment]
Mesela xamarin'de tek bi yerde kod yazıyosun (Cross platform), çıktı olarak ios ve android alabiliyorsun, react'ta da bu sistem var mı  ? 
- Videoların başlıklarında Web service yazısını görmeyince :)

**Comment by abdurrahmanekr** [comment]
@hulusimizrak dediğim gibi tek bir yerde kod yazıp derleyebilirsin ama uygulama içinde android ve ios uyumsuzlukları çıkabiliyor. Yani yazdığı projeye bağlı herşey. Xamarin hakkında bilgiye sahip değilim .net'e fazla yoğunlaşmadım. Eğer dediğin gibi xamarin üzerinde bile her işlemi yapabiliyorsan react native o şekilde değil. Örnek olarak react native [actionsheetios](https://facebook.github.io/react-native/docs/actionsheetios.html) bunun en bariz özelliği sadece ios üzerinde kullanabiliyorsun.

**Comment by hulusimizrak** [comment]
@abdurrahmanekr  Xamarin'de de 100% eşleşme yok bazı yerler renderer etmek gerekiyor.
Tek bi yerde derleyip çalıştırma için index.ios.js ve index.android.js için ayrı ayrı mı yazılıyor  ?

**Comment by hulusimizrak** [comment]
[http://www.avarekodcu.com/konu/16/react-native-ornek-login-uygulamasi-2-navigator-ile-yollarin-belirlenmesi](url) burada ios için yapılmış, bunu android'e çevirmek için yazılan kodları index.android.js 'e mi yazmak gerekiyor

**Comment by abdurrahmanekr** [comment]
@hulusimizrak evet öyle yapman gerekiyor. o ikisini tek bir dosyaya yönlendirirsen index.js diye oda çalışır. index.js diye dosya oluştur index.android.js içinde yazılanları index.js içine at, sonra **index.android.js** ve **index.ios.js** dosyalarına şunu yaz:
```import './index.js'```
bundan sonra index.android.js üzerinde yaptığın değişiklikleri artık index.ios.js üzerine taşımak zorunda kalmazsın
