### ISSUE TITLE
Sqlite multi seçim

### ISSUE THREAD

**Issue by ahmetozalp** [abdurrahmanekr/bana-istedigini-sor#80]
https://gist.github.com/peacecwz/6ea0a12c0021fe3d57288e043fcd73da şurdaki js yi kullanıyorum ama multı select olayını nasıl yapabilirim?,

`export const select = async (table: any, where: any = null, order: any = null): Promise<any> =>
  await service.select(table, '*', where, order);`

üstteki kod a import export edildi alttaki gibi kullanıyorum ama multı select olayını anlayamadım nasıl yapabilirim

```
select("notification_phone", ["userID", data.userID]).then(result_find => {

});
```

**Comment by abdurrahmanekr** [comment]
Yazdığınız kodda üç parametre var bunlar: table, where, order. Varsayılan '*' veriyor. Method columns değerini karşılamıyor ki. O kütüphane yerine [burayı](https://github.com/abdurrahmanekr/Websql-Sqlite-Service/blob/master/docs/API.md#select) kullanabilirsiniz.
