### ISSUE TITLE
Emülator

### ISSUE THREAD

**Issue by kraljesus** [abdurrahmanekr/bana-istedigini-sor#86]
Merhaba windows kullanıcısıyım run android dediğimde port8081 hatası veriyor java_home jdk yolunu bulamadığını belirtiyor ama heryere istenilen aşamaya göre yaptım androidstudio avd manager çalışıyor ama visual studio react-native run android dediğimde çalışmıyor

**Comment by abdurrahmanekr** [comment]
Merhaba, konu açılalı uzun zaman olmuş, sorunu çözmüşsünüzdür diye düşünüyorum, iyi günler.
