### ISSUE TITLE
Soradan Dosyalama

### ISSUE THREAD

**Issue by Kangarli** [abdurrahmanekr/bana-istedigini-sor#87]
Merhaba, ben uygulamayi React Native ile yazmaya baslarken bir hata yapmistim herseyi bitena ( App.js ) in icerisine yazdim soralar daha fazla kod eklenmesi ile onlayi dosyalara ayirmak zorunda kaldim simdi ayirdiktan sora hata aliyorum neden ? Soradan ayirmak olmuyormu yoksa importlarda hatali kod mu yaziyorum ondanmi ?

**Comment by abdurrahmanekr** [comment]
Nodejs'in import export'u ile aynı mantıkta çalışır, ancak webpack ile derlendiği için kepsi tek bir dosyaya atılır,  eğer import ve export kurallarının iyi bilirseniz yaparsınız. Şu an bir örnek veremiyorum.
