### ISSUE TITLE
Android Studio çözemediğim hata

### ISSUE THREAD

**Issue by onurozas** [abdurrahmanekr/bana-istedigini-sor#89]
Öncelikle merhabalar. Programlamada yeniyim ve Android Stuido kullanıyorum. Ancak Bir kodu çalıştırmak için runa bastığımda bu hatayı alıyorum:

FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Users\Onur\AppData\Local\Temp\Main_main__.gradle' line: 20

* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:Main.main()'.
   > SourceSet with name 'main' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s
18:32:05: Task execution finished 'Main.main()'.

Yardımcı olursanız çok mutlu olurum iyi günler.

**Comment by abdurrahmanekr** [comment]
Benim şu anki yetkinliğim react-native tarafında ve yaşadığınız sorunu tam olarak anlayamadım. Eğer bir android geliştiriciye sorarsanız yanıt bulacağınızı düşünüyorum. İyi günler.

**Comment by sonersimsekdev** [comment]
Şu zamanda bende bu sorunla cebelleşiyorum. Bende 1 haftadır macte windowsta stable beta alpha sürümlerinde denedim denedim çözemedim.
