### ISSUE TITLE
Kitap uygulaması için tavsiyeniz nedir ?

### ISSUE THREAD

**Issue by macingili** [abdurrahmanekr/bana-istedigini-sor#9]
Merhabalar ben bir kitap uygulaması yapmak istiyorum. (Kuranı kerim gibi , ya da mesnevi vs. gibi uygulamalar tarzında çalışma şekli olarak).
Bu konuda hangi uygulamaları kullanabilirim. İonic ile böyle bişey yapmamız mümkün olur mu ?
Ne kullanabilirim ?

Teşekkürler

**Comment by abdurrahmanekr** [comment]
@macingili İonic ile yapabilirsin. ionic'in pdf plugin'ini kullanırsın ya da kendin bir şekilde sayfaları oluşturursun. İonic pdf plugini var mı bilmiyorum. Tam olarak konuyu anlamadım. Uygulama örneği mi soruyorsun yoksa uygulamayı nasıl yapman gerektiğini mi ?

**Comment by macingili** [comment]
Merhabalar 

Aslında kitap uygulaması yapmak için bildiğiniz pratik bir yöntem var mı  yada bir araç tavsiyeniz olabilir mi diye sormuştum.

**Comment by macingili** [comment]
Yada şunu nasıl yapabilirim 
www klasörüne  bir klasör açsam  sayfaları html formatında buraya koysam daha sonra link ile buraya yönlendirsemde olur. Aslında ben bir denemek  için Cannot GET /www/ diye bir hata verdi.

app/assets klasörünün altınada çalışıyor ama üst navbar gelmiyor. Böyle birşeyde yapsamda olur Çünkü şunda uygulama çok kasıyor 10 sn de falan açılıyor. Pages altında çalışıyor. 100 den fazla sayfa var.

**Comment by abdurrahmanekr** [comment]
Bu konuda tavsiyem sayfaları eğer local'ine indireceksen docs diye bir dizin açıp içine page-1.json şeklinde dosyalar oluşturarak onların şu şekilde içerikler oluşturmandır.
```
{
	id: 1,
	page: 1,
	title: 'Başlık',
	subtitle: 'Alt Başlık':
	content: 'İçerik'
}
```
Sonra bu dosyaları controller içinde çağırarak sayfalara basarsın. Basit bir html sayfalama kullanırsın. Sayfa her değiştiğinde sadece sıradaki sayfayı çekersin. Eğer hepsini birden çekersen hâliyle yavaş olur.
Uzaktan çekeceksen iş daha kolay.
Projenin yapısını bilmediğimden dolayı diyeceğim tek şey uygulamanın performans testlerini yapman ver nerede sıkıntı çıkardığını bulman.

**Comment by macingili** [comment]
Aslında json mantığını çok düşündüm     json dosya olarak kayıt edip okumak istedim  çünkü en mantıklı olanı bu. http://www.avarekodcu.com/konu/9/ionic-2-kurulumu-kullanimi  bu makaleyi  referans alarak  localden json dosyası çağırmak için ayarlamaya çalıştım ama olmadı. Githubdan çekiyor ama localden çektiremedim.

**Comment by abdurrahmanekr** [comment]
@macingili hmm localdekini çekmek için bir soru sorulmuş [konu burası](https://stackoverflow.com/questions/38861663/angular-2-ionic-2-read-json-file-from-local-device-file-system) Belki buradaki işlemleri yaparak sonuç elde edebilirsin. Eğer yine olmazsa buradan tekrar haber et bende konuyu araştıracağım.

**Comment by macingili** [comment]
Abdurrahman bey alakanız için size çok teşekkür ederim ama çalışmadı hatada vermiyo consolo çıktıda yazmıyor. 

[Şöyle bir konu buldum ](https://stackoverflow.com/questions/40858663/how-to-get-the-data-from-local-json-to-the-html-page-using-ionic-2-typescript)cevabı onaylanmış bunu da düzenlemeye çalıştım ama başarılı olamadım. bu konuda yardımcı olabilir misiniz ?

**Comment by macingili** [comment]
Html dosyasını navbar ile birlikte açsamda işimi görecek aslında.

**Comment by abdurrahmanekr** [comment]
@macingili bizar geç cevap veriyorum kusura bakma, Ancak zaman bulabildim. Bir tane sıfırdan proje oluşturdum. Öncelikle ona bir provider ekledim [çevirdiğim yazı](http://www.avarekodcu.com/konu/9/ionic-2-kurulumu-kullanimi)daki gibi **github-users** adında içine şunları yazdım:
```typescript
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/Rx';
import 'rxjs/add/operator/map';

@Injectable()
export class GithubUsers {
  githubApiUrl = 'https://api.github.com';

  constructor(public http: Http) { }

  // Tüm github kullanıcılarını yükle
  load(): Observable<any> {
    return this.http.get(`assets/doc-0.json`)
      .map(res => res.json());
  }
}
```
sonra **src/docs/doc-0.json** diye dosya oluşturdum içindekiler : 
```json
{
	"id": 1,
	"page": 1,
	"title": "Başlık",
	"subtitle": "Alt Başlık",
	"content": "İçerik"
}
```
Sonra hello-ionic.ts dosyasında çağırdım o da şu şekilde :
```typescript
import { Component } from '@angular/core';
import {  GithubUsers } from '../../providers/github-users';

@Component({
	selector: 'page-hello-ionic',
	templateUrl: 'hello-ionic.html'
})

export class HelloIonicPage {
	constructor(private githubUsers: GithubUsers) {
		githubUsers.load().subscribe(users => {
	      debugger;
	    })
	}
}
```
Yani uzun lafın kısası 
```typescript
return this.http.get(`assets/doc-0.json`)
      .map(res => res.json());
```
şeklinde çağrılabiliyormuş. Umarım sorununu bu şekilde çözebilirsin

**Comment by macingili** [comment]
Allah razı olsun. Çok teşekkür ederim.
