### ISSUE TITLE
Componentin Render Edilmesi

### ISSUE THREAD

**Issue by onuraggez** [abdurrahmanekr/bana-istedigini-sor#91]
Merhaba Abdurrahman Bey,
Benim şöyle bir sorum var uygulama da bir sepet kullanıyorum ve bu sepetten ürün çıkardığım anda componenti tekrar baştan güncellemesini istiyorum. Fiyatın güncellenmesi için üürn çıkarıyorum fakat fiyat aynı kalıyor fiyatın değişmesi için componenti kapatıp açtığımda fiyat o zaman düzeliyor. Sanırım ürün sildiğim an tekrar render etmeliyim ama nasıl yapıcam bulamadım yardım ederseniz çok sevinirim. 
İyi Günler

**Comment by abdurrahmanekr** [comment]
react state kavramını iyi bir şekilde kurarsanız yaparsınız diye düşünüyorum, bunun için Üstün Özgür'ün dokümanlarından yararlanabilirsiniz.
