### ISSUE TITLE
sqllite bağlantısı

### ISSUE THREAD

**Issue by fatihsimsekk** [abdurrahmanekr/bana-istedigini-sor#92]
merhabalar ben react native ile yeni tanışmaya çalışıyorum fakat çok fazla java ile ilgili bilgim de yok benim yapmak istediğim veritabanına inputa girilen değeri kaydedip listelemesi yapmış olduğunuz böyle bir çalışma varmı acaba

**Comment by abdurrahmanekr** [comment]
"react native sqlite example" diye internette birçok kaynak mevcuttur benim baktığıma göre bir örnek uygulamam yok.
