### ISSUE TITLE
Google maps api

### ISSUE THREAD

**Issue by Alicoo1907** [abdurrahmanekr/bana-istedigini-sor#93]
Merhaba Google mapste gösterilen trafik yollarında ki +5dk +3dk gibi zaman göstergelerini nasıl çekebilirim .

**Comment by abdurrahmanekr** [comment]
Nasıl yapıldığını bilmiyorum ama firebase maps api’ye bakarsanız bulursunuz
büyük ihtimal

3 Eki 2019 Per, saat ÖÖ 11:29 tarihinde Ali ÇOBAN <notifications@github.com>
şunu yazdı:
