### ISSUE TITLE
Merhabalar, Java dilinde yardıma ihtiyacım var yardımcı olabilir misiniz ? 

### ISSUE THREAD

**Issue by xstormbringer** [abdurrahmanekr/bana-istedigini-sor#94]
İyi Günler. Üniversite YBS öğrencisiyim ve hocamızın verdiği bir ödevde yardıma ihtiyacım var. Ödev 3 Topun forum üzerinde hareket ettirilmesi fakat birbirlerine çarptıklarında yön değiştirmeleri gerekiyor ve "Çarpışma testi (collision detection, hittest) için ipuçu; Rectangle nesnesinin intersects komutu" bu notu paylaşmış. Eğer bilginiz var ise yardımcı olursanız sevinirim.

**Comment by abdurrahmanekr** [comment]
Bu konuda size yardımcı olamayacağım malesef
