### ISSUE TITLE
RN[0.60] Resimler için filtre

### ISSUE THREAD

**Issue by meftunca** [abdurrahmanekr/bana-istedigini-sor#95]
Yazdığım proje için filtreleme yapmam gerekiyor. react-native-gl kullanmak istedim fakat react-native-webgl bağımlılığı sorun çıkardığı için kullanamadım. Bu konuda bir fikriniz var mı ?

**Comment by abdurrahmanekr** [comment]
Merhaba sorunuza geç cevap verdiğim için üzgünüm, filtreleme derken tam olarak bir resmi filtrelemekten mi bahsediyorsunuz? Bunu soruyorsanız hiç uğraşmadım malesef :/
