### ISSUE TITLE
Vue & Electron

### ISSUE THREAD

**Issue by yunusemremert** [abdurrahmanekr/bana-istedigini-sor#96]
Merhaba,

Electron içerisinde vue ile proje geliştirmesi yapacağız fakat bir şey sormak isterim. Vue'nun route mantığını kullanacağım ama başka sayfada da bir linke tıkladığım da chromium penceresini kullanarak işlem yaptırmak istiyorum bu mümkün müdür ?

**Comment by abdurrahmanekr** [comment]
Vue' route mekanizmasını bilmiyorum ancak eğer uygulamanın içinde yeni bir pencere açmak gibi bir şey soruyorsanız mümkün. `window.open` kullanabilirsiniz. Tarayıcıda açmak için [shell.openExternal](https://electronjs.org/docs/api/shell#shellopenexternalurl-options) kullanabilirsiniz.
