### ISSUE TITLE
Reklam Ekleme Sorunu React-Native Adcolony Ads, Unity Ads, Vungle Ads

### ISSUE THREAD

**Issue by HardMan1453** [abdurrahmanekr/bana-istedigini-sor#98]
Merhaba Abdurrahman Bey;
React-Native kullanarak bir uygulama geliştirdim ve reklam eklemek istiyorum. Google reklamları dışında Unity Ads, Adcolony Ads veya Vungle Ads olarak ama SDK olarak baktığımda Javascript destek vermiyorlar. Bu sorunu nasıl çözebilirim React-Native üzerinde yazılmış uygulamaya nasıl reklam eklerim. Google admob  ve facebook Audience dışında.
Acil Destek

**Comment by abdurrahmanekr** [comment]
Merhabalar, açıkçası google admob'dan başka bir SDK kullanmadım. Size bu konuda malesef yardımcı olamayacağım.
