### ISSUE TITLE
React Native Admob

### ISSUE THREAD

**Issue by uguripek** [abdurrahmanekr/bana-istedigini-sor#99]
Merhabalar hocam,
Admob ile ilgili yayınladığınız makaleyi okudum. Söylediklerinizi harfiyen yapmama rağmen reklam çalışıyor fakat test reklamı çalışıyor. Uygulamayı yayınlayacağım ama Test Reklamı yazısını bir türlü kaldıramadım.

**Comment by abdurrahmanekr** [comment]
Uygulamanız debug olarak çalışıyorsa test reklamını görürsünüz, release için bu çıkmayacaktır

**Comment by uguripek** [comment]
Uygulamayı nasıl release çalıştırabilirim? Apk sını alırken release seçeneğini seçiyorum ama yine de telefonda da test reklamı gözüküyor

**Comment by abdurrahmanekr** [comment]
Release derleme alabilmek için bu adımları takip edebilirsiniz:  https://react-native.org/doc/signed-apk-android.html
